package cn.gc80.datamodel.learning;

import cn.gc80.datamodel.res.ResCourse;
import cn.gc80.datamodel.res.ResCourseware;
import cn.gc80.datamodel.sysbase.SysCode;
import cn.gc80.datamodel.sysbase.SysUser;

/**
 * LearnUserCourse generated by MyEclipse Persistence Tools
 */

public class LearnUserCourse implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -1935518345544777811L;

	private String id;

	private ResCourse resCourse;

	private SysUser sysUser;

	private ResCourseware resCourseware;

	private String studystatus;

	private Long time = 0l;

	private Long hours = 0l;

	private String firsttime = "";

	private String lasttime = "";

	private String completetime = "";

	private String ensuretime = "";

	private String status = "02";

	private Long duration = 0l;
	
	private Double examscore;

	private String delflag = "02";
	
	private String minute;
	
	private Long hasCredit = 0l;
	
	private int percent;
	
	private Long timelimit;
	
	private Long allowAttempt;

	// Constructors

	public Long getAllowAttempt() {
		return allowAttempt;
	}

	public void setAllowAttempt(Long allowAttempt) {
		this.allowAttempt = allowAttempt;
	}

	public Long getTimelimit() {
		return timelimit;
	}

	public void setTimelimit(Long timelimit) {
		this.timelimit = timelimit;
	}

	public int getPercent() {
		return percent;
	}

	public void setPercent(int percent) {
		this.percent = percent;
	}

	/** default constructor */
	public LearnUserCourse() {
	}
	
	
	/** minimal constructor */
	
	public LearnUserCourse(String id,String studystatus){
		this.id = id;
		this.studystatus = studystatus;
	}
	public LearnUserCourse(ResCourse resCourse, String studystatus,
			Long time, Long hours, String delflag) {
		this.resCourse = resCourse;
		this.studystatus = studystatus;
		this.time = time;
		this.hours = hours;
		this.delflag = delflag;
	}
	
	public LearnUserCourse(String id,String firsttime,String lasttime,String studystatus,String status,Long hasCredit,String delflag){
		this.id = id;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.studystatus = studystatus;
		this.status = status;
		this.hasCredit = hasCredit;
		this.delflag = delflag;
	}
	public LearnUserCourse(String id,String firsttime,String lasttime,String studystatus,String status,Long hasCredit,String delflag,Long allowAttempt){
		this.id = id;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.studystatus = studystatus;
		this.status = status;
		this.hasCredit = hasCredit;
		this.delflag = delflag;
		this.allowAttempt = allowAttempt;
	}
	public LearnUserCourse(String id,Long time,String firsttime,String lasttime,String studystatus,String status,Long hasCredit,String delflag,Long allowAttempt){
		this.id = id;
		this.time = time;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.studystatus = studystatus;
		this.status = status;
		this.hasCredit = hasCredit;
		this.delflag = delflag;
		this.allowAttempt = allowAttempt;
	}
	
	public LearnUserCourse(String id,Long time,String firsttime,String lasttime,String ensuretime,String studystatus,String status,Long hasCredit,String delflag,Long allowAttempt,String codeNo,String courseid,String CName,long CCredithour,String isExam,long creditnum){
		this.id = id;
		this.time = time;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.ensuretime = ensuretime;
		this.studystatus = studystatus;
		this.status = status;
		this.hasCredit = hasCredit;
		this.delflag = delflag;
		this.allowAttempt = allowAttempt;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		course.setCCredithour(CCredithour);
		course.setIsExam(isExam);
		course.setSysCode(code);
		this.resCourse = course;
		ResCourseware courseware = new ResCourseware();
		courseware.setCreditnum(creditnum);
		this.resCourseware = courseware;
	}
	
	public LearnUserCourse(String id,Long time,String firsttime,String lasttime,String ensuretime,String studystatus,String status,Long hasCredit,String delflag,Long allowAttempt,String codeNo,String courseid,String CName,long CCredithour,String isExam,long creditnum,long cwPeriod){
		this.id = id;
		this.time = time;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.ensuretime = ensuretime;
		this.studystatus = studystatus;
		this.status = status;
		this.hasCredit = hasCredit;
		this.delflag = delflag;
		this.allowAttempt = allowAttempt;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		course.setCCredithour(CCredithour);
		course.setIsExam(isExam);
		course.setSysCode(code);
		this.resCourse = course;
		ResCourseware courseware = new ResCourseware();
		courseware.setCreditnum(creditnum);
		courseware.setCwPeriod(cwPeriod);
		this.resCourseware = courseware;
	}
	
	public LearnUserCourse(String id,String firsttime,String lasttime,String completetime,String studystatus,Long time,Long hours){
		this.id = id;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.completetime = completetime;
		this.studystatus = studystatus;
		this.time = time;
		this.hours = hours;
	}
	public LearnUserCourse(String id,String userid,String userName,String realname,String courseid,String CName,String coursewareid,String cwName,String lasttime,Long time,String studystatus){
		this.id = id;
		SysUser user = new SysUser();
		user.setId(userid);
		user.setUserName(userName);
		user.setRealname(realname);
		this.sysUser = user;
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		this.resCourse = course;
		ResCourseware courseware = new ResCourseware();
		courseware.setId(coursewareid);
		courseware.setCwName(cwName);
		this.resCourseware = courseware;
		this.lasttime = lasttime;
		this.time = time;
		this.studystatus = studystatus;
	}
	
	public LearnUserCourse(String id,String userid,String userName,String realname,String codeNo, String courseid,String CName,String coursewareid,String cwName,String lasttime,Long time,String studystatus){
		this.id = id;
		SysUser user = new SysUser();
		user.setId(userid);
		user.setUserName(userName);
		user.setRealname(realname);
		this.sysUser = user;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		course.setSysCode(code);
		this.resCourse = course;
		ResCourseware courseware = new ResCourseware();
		courseware.setId(coursewareid);
		courseware.setCwName(cwName);
		this.resCourseware = courseware;
		this.lasttime = lasttime;
		this.time = time;
		this.studystatus = studystatus;
	}
	
	public LearnUserCourse(String id,String codeNo, String courseid,String CName,String coursewareid,String cwName){
		this.id = id;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		course.setSysCode(code);
		this.resCourse = course;
		ResCourseware courseware = new ResCourseware();
		courseware.setId(coursewareid);
		courseware.setCwName(cwName);
		this.resCourseware = courseware;
	}
	
	public LearnUserCourse(String id,String userid,String realname,String CName,Double CPrice,Long CCredithour,String CImage,String CRecommend,String studystatus,Long hasCredit,String completetime){
		this.id = id;
		SysUser user=new SysUser();
		user.setId(userid);
		user.setRealname(realname);
		this.sysUser = user;
		
		ResCourse resCourse= new ResCourse();
		resCourse.setCName(CName);
		resCourse.setCPrice(CPrice);
		resCourse.setCCredithour(CCredithour);
		resCourse.setCImage(CImage);
		resCourse.setCRecommend(CRecommend);
		this.resCourse=resCourse;
		
		this.studystatus = studystatus;
		this.hasCredit = hasCredit;
		this.completetime = completetime;
	}
	public LearnUserCourse(String id,String userid,String realname,String courseId,String courseName,String cwId,String cwName,Long cwPeriod,String studystatus){
		this.id = id;
		SysUser user=new SysUser();
		user.setId(userid);
		user.setRealname(realname);
		this.sysUser = user;
		
		ResCourse resCourse= new ResCourse();
		resCourse.setId(courseId);
		resCourse.setCName(courseName);
		this.resCourse=resCourse;
		
		ResCourseware resCourseware= new ResCourseware();
		resCourseware.setId(cwId);
		resCourseware.setCwName(cwName);
		resCourseware.setCwPeriod(cwPeriod);
		this.resCourseware = resCourseware;
		this.studystatus = studystatus;
	}
	public LearnUserCourse(String id,String userid,String realname,String courseId,String courseName,String cwId,String cwName,String studystatus,Long hasCredit,Long creditnum,String lasttime){
		this.id = id;
		SysUser user=new SysUser();
		user.setId(userid);
		user.setRealname(realname);
		this.sysUser = user;
		
		ResCourse resCourse= new ResCourse();
		resCourse.setId(courseId);
		resCourse.setCName(courseName);
		this.resCourse=resCourse;
		
		ResCourseware resCourseware= new ResCourseware();
		resCourseware.setId(cwId);
		resCourseware.setCwName(cwName);
		resCourseware.setCreditnum(creditnum);
		this.resCourseware = resCourseware;
		this.studystatus = studystatus;
		this.hasCredit = hasCredit;
		this.lasttime = lasttime;
	}
	public LearnUserCourse(String id,String userid,String realname,String courseId,String courseName,String cwId,String cwName,String studystatus,Long hasCredit,Double examscore,Long creditnum,String lasttime,String codeNo){
		this.id = id;
		SysUser user=new SysUser();
		user.setId(userid);
		user.setRealname(realname);
		this.sysUser = user;
		
		ResCourse resCourse= new ResCourse();
		resCourse.setId(courseId);
		resCourse.setCName(courseName);
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		resCourse.setSysCode(code);
		this.resCourse=resCourse;
		
		ResCourseware resCourseware= new ResCourseware();
		resCourseware.setId(cwId);
		resCourseware.setCwName(cwName);
		resCourseware.setCreditnum(creditnum);
		this.resCourseware = resCourseware;
		this.studystatus = studystatus;
		this.hasCredit = hasCredit;
		this.examscore = examscore;
		this.lasttime = lasttime;
	}
	
	public LearnUserCourse(String id,String userid,String realname,String courseId,String courseName,String isExam,String cwId,String cwName,String studystatus,Long hasCredit,Double examscore,Long creditnum,String lasttime,String codeNo){
		this.id = id;
		SysUser user=new SysUser();
		user.setId(userid);
		user.setRealname(realname);
		this.sysUser = user;
		
		ResCourse resCourse= new ResCourse();
		resCourse.setId(courseId);
		resCourse.setCName(courseName);
		resCourse.setIsExam(isExam);
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		resCourse.setSysCode(code);
		this.resCourse=resCourse;
		
		ResCourseware resCourseware= new ResCourseware();
		resCourseware.setId(cwId);
		resCourseware.setCwName(cwName);
		resCourseware.setCreditnum(creditnum);
		this.resCourseware = resCourseware;
		this.studystatus = studystatus;
		this.hasCredit = hasCredit;
		this.examscore = examscore;
		this.lasttime = lasttime;
	}
	
	public LearnUserCourse(String id,String userid,String userName,String courseId,String courseName,String courseWareId,String cwName,Long creditnum, Long hasCredit,Long time,Long hours,int percent){
		this.id=id;
		this.hasCredit = hasCredit;
		this.time = time;
		SysUser user=new SysUser();
		user.setId(userid);
		user.setUserName(userName);
		this.sysUser=user;
		ResCourse resCourse= new ResCourse();
		resCourse.setId(courseId);
		resCourse.setCName(courseName);
		this.resCourse=resCourse;
		ResCourseware resCourseWare= new ResCourseware();
		resCourseWare.setId(courseWareId);
		resCourseWare.setCwName(cwName);
		resCourseWare.setCreditnum(creditnum);
		this.resCourseware=resCourseWare;
		
		this.hours=hours;
		this.percent=percent;
	}
	public LearnUserCourse(String id,String userid,String userName,String courseId,String courseName,String courseWareId,String cwName,Long creditnum, Long hasCredit,Long time,String studystatus){
		this.id=id;
		this.hasCredit = hasCredit;
		this.time = time;
		this.studystatus = studystatus;
		SysUser user=new SysUser();
		user.setId(userid);
		user.setUserName(userName);
		this.sysUser=user;
		ResCourse resCourse= new ResCourse();
		resCourse.setId(courseId);
		resCourse.setCName(courseName);
		this.resCourse=resCourse;
		ResCourseware resCourseWare= new ResCourseware();
		resCourseWare.setId(courseWareId);
		resCourseWare.setCwName(cwName);
		resCourseWare.setCreditnum(creditnum);
		this.resCourseware=resCourseWare;
	}
	/** full constructor */
	public LearnUserCourse(ResCourse resCourse,
			SysUser sysUser, ResCourseware resCourseware,
			String studystatus, Long time, Long hours, String firsttime,
			String lasttime, String completetime, String ensuretime,
			String status, Long duration, String delflag) {
		this.resCourse = resCourse;
		this.sysUser = sysUser;
		this.resCourseware = resCourseware;
		this.studystatus = studystatus;
		this.time = time;
		this.hours = hours;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.completetime = completetime;
		this.ensuretime = ensuretime;
		this.status = status;
		this.duration = duration;
		this.delflag = delflag;
	}
	
	public LearnUserCourse(String userId,String courseId,String lasttime) {
		ResCourse resCourse=new ResCourse();
		resCourse.setId(courseId);
		this.resCourse = resCourse;
		SysUser sysUser=new SysUser();
		sysUser.setId(userId);
		this.sysUser = sysUser;
		this.lasttime=lasttime;
	}
	
	//,resCourse.sysCode.sysCode.codeNo,resCourse.sysCode.codeNo,resCourse.CCredithour,resCourseware.cwPeriod;
	public LearnUserCourse(String id,String userId,String courseId,String courseName,String isExam,String cwId,String cwName,String studystatus,Long hasCredit,Long creditnum,
			String codePCodeNo,String codeNo,Long CCredithour,Long cwPeriod){
		this.id = id;
		
		SysUser user=new SysUser();
		user.setId(userId);
		this.sysUser=user;
		
		ResCourse resCourse= new ResCourse();
		resCourse.setId(courseId);
		resCourse.setCName(courseName);
		resCourse.setIsExam(isExam);
		resCourse.setCCredithour(CCredithour);
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		SysCode cp= new SysCode();
		cp.setCodeNo(codePCodeNo);
		code.setSysCode(cp);
		resCourse.setSysCode(code);
		this.resCourse=resCourse;
		
		ResCourseware resCourseware= new ResCourseware();
		resCourseware.setId(cwId);
		resCourseware.setCwName(cwName);
		resCourseware.setCreditnum(creditnum);
		resCourseware.setCwPeriod(cwPeriod);
		this.resCourseware = resCourseware;
		this.studystatus = studystatus;
		this.hasCredit = hasCredit;
		
	}
	
	public LearnUserCourse(String id,String firsttime,String lasttime,String completetime,String ensuretime,Long time){
		this.id = id;
		this.firsttime = firsttime;
		this.lasttime = lasttime;
		this.completetime = completetime;
		this.ensuretime=ensuretime;
		this.time = time;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStudystatus() {
		return this.studystatus;
	}

	public void setStudystatus(String studystatus) {
		this.studystatus = studystatus;
	}

	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	public Long getHours() {
		return this.hours;
	}

	public void setHours(Long hours) {
		this.hours = hours;
	}

	public String getFirsttime() {
		return this.firsttime;
	}

	public void setFirsttime(String firsttime) {
		this.firsttime = firsttime;
	}

	public String getLasttime() {
		return this.lasttime;
	}

	public void setLasttime(String lasttime) {
		this.lasttime = lasttime;
	}

	public String getCompletetime() {
		return this.completetime;
	}

	public void setCompletetime(String completetime) {
		this.completetime = completetime;
	}

	public String getEnsuretime() {
		return this.ensuretime;
	}

	public void setEnsuretime(String ensuretime) {
		this.ensuretime = ensuretime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getDuration() {
		return this.duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public String getMinute() {
		return this.minute;
	}

	public void setMinute(String minute) {
		this.minute = minute;
	}

	public Long getHasCredit() {
		return hasCredit;
	}

	public void setHasCredit(Long hasCredit) {
		this.hasCredit = hasCredit;
	}

	public ResCourse getResCourse() {
		return resCourse;
	}

	public void setResCourse(ResCourse resCourse) {
		this.resCourse = resCourse;
	}

	public ResCourseware getResCourseware() {
		return resCourseware;
	}

	public void setResCourseware(ResCourseware resCourseware) {
		this.resCourseware = resCourseware;
	}

	public SysUser getSysUser() {
		return sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Double getExamscore() {
		return examscore;
	}

	public void setExamscore(Double examscore) {
		this.examscore = examscore;
	}

}