package cn.gc80.datamodel.learning;

import cn.gc80.datamodel.res.ResChapter;
import cn.gc80.datamodel.res.ResCourse;
import cn.gc80.datamodel.res.ResCourseware;
import cn.gc80.datamodel.sysbase.SysUser;

/**
 * LearnUserChapter generated by MyEclipse Persistence Tools
 */

public class LearnUserChapter implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -2262178639203060334L;

	private String id;

	private ResCourse resCourse;

	private SysUser sysUser;

	private ResChapter resChapter;

	private ResCourseware resCourseware;

	private String resUrl = "";

	private Long sequence = 0l;

	private String lessonstatus = "";

	private Long time = 0l;

	private Long hours = 0l;
	
	private String starttime = "";

	private String endtime = "";

	private String lasttime = "";

	private String score = "";

	private String scotype = "";
	
	private String trackMode = "";
	
	private String lessonLocation = "";
	
	private String suspendData = "";
	
	private Long totalHours;
	
	private Long laststarttime = 0l;
	
	// Constructors
	public LearnUserChapter(String lessonstatus){
		this.lessonstatus = lessonstatus;
	}
	public LearnUserChapter(String id,Long hours){
		this.id= id;
		this.hours = hours;
	}
	public LearnUserChapter(String id,String starttime,String lasttime,String lessonstatus,String chapterid,String chapterTitle,Long period,Long hours,Long time){
		this.id = id;
		this.starttime = starttime;
		this.lasttime = lasttime;
		this.lessonstatus = lessonstatus;
		ResChapter chapter = new ResChapter();
		chapter.setId(chapterid);
		chapter.setChapterTitle(chapterTitle);
		chapter.setPeriod(period);
		this.resChapter = chapter;
		this.hours = hours;
		this.time = time;
		
	}
	public LearnUserChapter(String id,Long hours,String lessonstatus,String chapterid,Long period){
		this.id= id;
		this.hours = hours;
		this.lessonstatus = lessonstatus;
		ResChapter chapter = new ResChapter();
		chapter.setId(chapterid);
		chapter.setPeriod(period);
		this.resChapter = chapter;
	}
	
	public LearnUserChapter(String id,Long hours,Long time,String starttime,String lessonstatus){
		this.id= id;
		this.hours = hours;
		this.time = time;
		this.starttime = starttime;
		this.lessonstatus = lessonstatus;
	}
	
	public LearnUserChapter(String id,Long hours,Long time,String starttime,String lessonstatus,String lessonLocation,String suspendData,String chapterid,Long period){
		this.id= id;
		this.hours = hours;
		this.time = time;
		this.starttime = starttime;
		this.lessonstatus = lessonstatus;
		this.lessonLocation = lessonLocation;
		this.suspendData = suspendData;
		ResChapter chapter = new ResChapter();
		chapter.setId(chapterid);
		chapter.setPeriod(period);
		this.resChapter = chapter;
	}
	
	public LearnUserChapter(String id,Long hours,Long time,String starttime,String lasttime,String endtime,String lessonstatus,String lessonLocation,String suspendData,Long laststarttime,Long totalHourse){
		this.id= id;
		this.hours = hours;
		this.time = time;
		this.starttime = starttime;
		this.lasttime = lasttime;
		this.endtime = endtime;
		this.lessonstatus = lessonstatus;
		this.lessonLocation = lessonLocation;
		this.suspendData = suspendData;
		this.laststarttime = laststarttime;
		this.totalHours = totalHourse;
	}
	
	public Long getLaststarttime() {
		return laststarttime;
	}
	public void setLaststarttime(Long laststarttime) {
		this.laststarttime = laststarttime;
	}
	public Long getTotalHours() {
		return totalHours;
	}
	public void setTotalHours(Long totalHours) {
		this.totalHours = totalHours;
	}
	public String getLessonLocation() {
		return lessonLocation;
	}

	public void setLessonLocation(String lessonLocation) {
		this.lessonLocation = lessonLocation;
	}

	/** default constructor */
	public LearnUserChapter() {
	}

	/** minimal constructor */
	public LearnUserChapter(ResCourse resCourse,
			SysUser sysUser, ResChapter resChapter,
			ResCourseware resCourseware, String resUrl, Long time,
			Long hours) {
		this.resCourse = resCourse;
		this.sysUser = sysUser;
		this.resChapter = resChapter;
		this.resCourseware = resCourseware;
		this.resUrl = resUrl;
		this.time = time;
		this.hours = hours;
	}

	/** full constructor */
	public LearnUserChapter(ResCourse resCourse,
			SysUser sysUser, ResChapter resChapter,
			ResCourseware resCourseware, String resUrl, Long sequence,
			String lessonstatus, Long time, Long hours, String starttime,
			String endtime, String lasttime, String score, String scotype) {
		this.resCourse = resCourse;
		this.sysUser = sysUser;
		this.resChapter = resChapter;
		this.resCourseware = resCourseware;
		this.resUrl = resUrl;
		this.sequence = sequence;
		this.lessonstatus = lessonstatus;
		this.time = time;
		this.hours = hours;
		this.starttime = starttime;
		this.endtime = endtime;
		this.lasttime = lasttime;
		this.score = score;
		this.scotype = scotype;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public ResChapter getResChapter() {
		return resChapter;
	}

	public void setResChapter(ResChapter resChapter) {
		this.resChapter = resChapter;
	}

	public ResCourse getResCourse() {
		return resCourse;
	}

	public void setResCourse(ResCourse resCourse) {
		this.resCourse = resCourse;
	}

	public ResCourseware getResCourseware() {
		return resCourseware;
	}

	public void setResCourseware(ResCourseware resCourseware) {
		this.resCourseware = resCourseware;
	}

	public SysUser getSysUser() {
		return sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public String getResUrl() {
		return this.resUrl;
	}

	public void setResUrl(String resUrl) {
		this.resUrl = resUrl;
	}

	public Long getSequence() {
		return this.sequence;
	}

	public void setSequence(Long sequence) {
		this.sequence = sequence;
	}

	public String getLessonstatus() {
		return this.lessonstatus;
	}

	public void setLessonstatus(String lessonstatus) {
		this.lessonstatus = lessonstatus;
	}

	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	public Long getHours() {
		return this.hours;
	}

	public void setHours(Long hours) {
		this.hours = hours;
	}

	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	public String getLasttime() {
		return this.lasttime;
	}

	public void setLasttime(String lasttime) {
		this.lasttime = lasttime;
	}

	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	public String getScotype() {
		return this.scotype;
	}

	public void setScotype(String scotype) {
		this.scotype = scotype;
	}

	public String getTrackMode() {
		return trackMode;
	}

	public void setTrackMode(String trackMode) {
		this.trackMode = trackMode;
	}
	public String getSuspendData() {
		return suspendData;
	}
	public void setSuspendData(String suspendData) {
		this.suspendData = suspendData;
	}
	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

}