package cn.gc80.datamodel.res;

import java.util.Set;

import cn.gc80.datamodel.sysbase.SysCode;

/**
 * YfssResBook generated by MyEclipse Persistence Tools
 */

public class ResBook implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -428526082659205821L;

	private String id;

	private SysCode sysCodeByBookPaper;

	private SysCode sysCodeByCodeId;

	private String bookName;

	private String bookDesc;

	private String bookAuthor;

	private String bookPublisher;

	private String bookPubTime;

	private String bookIsbn;

	private Double bookCost;

	private Double bookPrice;

	private Double bookDiscount;

	private String bookEdition;

	private String bookPrintTime;

	private Long bookWords;

	private Long bookPages;

	private String bookFolio;

	private String bookBoxing;

	private String bookReleaseFlag;

	private String bookImage;
	
	private Long amount;

	private String lastedittime;

	private String createtime;

	private String lasteditor;

	private String creator;

	private String delflag;

	// Constructors

	/** default constructor */
	public ResBook() {
	}

	public ResBook(String id,String bookName,Double bookPrice){
		this.id = id;
		this.bookName = bookName;
		this.bookPrice = bookPrice;
	}
	/** minimal constructor */
	public ResBook(String bookName, String delflag) {
		this.bookName = bookName;
		this.delflag = delflag;
	}
	public ResBook(String bookName, String id,String bookImage) {
		this.bookName = bookName;
		this.id=id;
		this.bookImage = bookImage;
	}
	public ResBook(String bookName, String id,String bookImage,Double bookCost,Double bookPrice) {
		this.bookName = bookName;
		this.id=id;
		this.bookImage = bookImage;
		this.bookCost=bookCost;
		this.bookPrice=bookPrice;
	}
	/** full constructor */
	public ResBook(SysCode sysCodeByBookPaper,
			SysCode sysCodeByCodeId, String bookName, String bookDesc,
			String bookAuthor, String bookPublisher, String bookPubTime,
			String bookIsbn, Double bookCost, Double bookPrice,
			Double bookDiscount, String bookEdition, String bookPrintTime,
			Long bookWords, Long bookPages, String bookFolio,
			String bookBoxing, String bookReleaseFlag, String bookImage,
			String lastedittime, String createtime, String lasteditor,
			String creator, String delflag, Set yfssResCourseBooks,
			Set yfssEOrderDetails) {
		this.sysCodeByBookPaper = sysCodeByBookPaper;
		this.sysCodeByCodeId = sysCodeByCodeId;
		this.bookName = bookName;
		this.bookDesc = bookDesc;
		this.bookAuthor = bookAuthor;
		this.bookPublisher = bookPublisher;
		this.bookPubTime = bookPubTime;
		this.bookIsbn = bookIsbn;
		this.bookCost = bookCost;
		this.bookPrice = bookPrice;
		this.bookDiscount = bookDiscount;
		this.bookEdition = bookEdition;
		this.bookPrintTime = bookPrintTime;
		this.bookWords = bookWords;
		this.bookPages = bookPages;
		this.bookFolio = bookFolio;
		this.bookBoxing = bookBoxing;
		this.bookReleaseFlag = bookReleaseFlag;
		this.bookImage = bookImage;
		this.lastedittime = lastedittime;
		this.createtime = createtime;
		this.lasteditor = lasteditor;
		this.creator = creator;
		this.delflag = delflag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public SysCode getSysCodeByBookPaper() {
		return sysCodeByBookPaper;
	}

	public void setSysCodeByBookPaper(SysCode sysCodeByBookPaper) {
		this.sysCodeByBookPaper = sysCodeByBookPaper;
	}

	public SysCode getSysCodeByCodeId() {
		return sysCodeByCodeId;
	}

	public void setSysCodeByCodeId(SysCode sysCodeByCodeId) {
		this.sysCodeByCodeId = sysCodeByCodeId;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getBookDesc() {
		return this.bookDesc;
	}

	public void setBookDesc(String bookDesc) {
		this.bookDesc = bookDesc;
	}

	public String getBookAuthor() {
		return this.bookAuthor;
	}

	public void setBookAuthor(String bookAuthor) {
		this.bookAuthor = bookAuthor;
	}

	public String getBookPublisher() {
		return this.bookPublisher;
	}

	public void setBookPublisher(String bookPublisher) {
		this.bookPublisher = bookPublisher;
	}

	public String getBookPubTime() {
		return this.bookPubTime;
	}

	public void setBookPubTime(String bookPubTime) {
		this.bookPubTime = bookPubTime;
	}

	public String getBookIsbn() {
		return this.bookIsbn;
	}

	public void setBookIsbn(String bookIsbn) {
		this.bookIsbn = bookIsbn;
	}

	public Double getBookCost() {
		return this.bookCost;
	}

	public void setBookCost(Double bookCost) {
		this.bookCost = bookCost;
	}

	public Double getBookPrice() {
		return this.bookPrice;
	}

	public void setBookPrice(Double bookPrice) {
		this.bookPrice = bookPrice;
	}

	public Double getBookDiscount() {
		return this.bookDiscount;
	}

	public void setBookDiscount(Double bookDiscount) {
		this.bookDiscount = bookDiscount;
	}

	public String getBookEdition() {
		return this.bookEdition;
	}

	public void setBookEdition(String bookEdition) {
		this.bookEdition = bookEdition;
	}

	public String getBookPrintTime() {
		return this.bookPrintTime;
	}

	public void setBookPrintTime(String bookPrintTime) {
		this.bookPrintTime = bookPrintTime;
	}

	public Long getBookWords() {
		return this.bookWords;
	}

	public void setBookWords(Long bookWords) {
		this.bookWords = bookWords;
	}

	public Long getBookPages() {
		return this.bookPages;
	}

	public void setBookPages(Long bookPages) {
		this.bookPages = bookPages;
	}

	public String getBookFolio() {
		return this.bookFolio;
	}

	public void setBookFolio(String bookFolio) {
		this.bookFolio = bookFolio;
	}

	public String getBookBoxing() {
		return this.bookBoxing;
	}

	public void setBookBoxing(String bookBoxing) {
		this.bookBoxing = bookBoxing;
	}

	public String getBookReleaseFlag() {
		return this.bookReleaseFlag;
	}

	public void setBookReleaseFlag(String bookReleaseFlag) {
		this.bookReleaseFlag = bookReleaseFlag;
	}

	public String getBookImage() {
		return this.bookImage;
	}

	public void setBookImage(String bookImage) {
		this.bookImage = bookImage;
	}

	public String getLastedittime() {
		return this.lastedittime;
	}

	public void setLastedittime(String lastedittime) {
		this.lastedittime = lastedittime;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getLasteditor() {
		return this.lasteditor;
	}

	public void setLasteditor(String lasteditor) {
		this.lasteditor = lasteditor;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public Long getAmount() {
		return amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

}