package cn.gc80.datamodel.res;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import cn.gc80.datamodel.sysbase.SysCode;
import cn.gc80.datamodel.sysbase.SysTeacher;
/**
 * ResCourse generated by MyEclipse Persistence Tools
 */

public class ResCourse implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 8738893493841592695L;

	private String id;

	private SysCode sysCode;
	
	private SysTeacher sysTeacher;

	private ResCourseware resCourseware;
	
	private String CNo;

	private String CName;

	private String CDesc;

	private String CMode;

	private String CStarttime;

	private String CEndtime;

	private Double CPeriod;

	private Long CCredithour;

	private Long CDuration;

	private Double CCost;

	private Double CPrice;

	private String CType;

	private String CImage = "";
	
	private String CYear;

	private Long CChooseCount;

	private Long COrdernum;

	private String CReleaseFlag;

	private String CRecommend;

	private String creator;

	private String lasteditor;

	private String createtime;

	private String lastedittime;

	private String isExam;
	
	private String delflag;
	
	private List cwList;
	private List  teacherList;
	private List bookList;
	
	private String demoLaunch;
	
	private long sellAmount;
	private double sellMoney;
	private long questionCount;
	private double avgEva;
	
	private Long goodNum;
	private Long studyNum;
	private String classNo;
	//是否热门课程
	private String isHot;
	//是否试听
	private String isAudition;
	
	//是否购买过，赋值用
	private String isShopping;

	// Constructors
	
	public ResCourse(String id, String CNo, String CName, Long CCredithour,Double CPrice, String CReleaseFlag, Long COrdernum,String sysCodeId, String sysCodeCodeNo) {
		this.id=id;
		this.CNo=CNo;
		this.CName=CName;
		this.CCredithour=CCredithour;
		this.CPrice=CPrice;
		this.CReleaseFlag=CReleaseFlag;
		this.COrdernum=COrdernum;
		SysCode sCode=new SysCode();
		sCode.setId(sysCodeId);
		sCode.setCodeNo(sysCodeCodeNo);
		this.sysCode=sCode;
	}
	public long getQuestionCount() {
		return questionCount;
	}

	public void setQuestionCount(long questionCount) {
		this.questionCount = questionCount;
	}

	public long getSellAmount() {
		return sellAmount;
	}

	public void setSellAmount(long sellAmount) {
		this.sellAmount = sellAmount;
	}

	public double getSellMoney() {
		return sellMoney;
	}

	public void setSellMoney(double sellMoney) {
		this.sellMoney = sellMoney;
	}

	public String getDemoLaunch() {
		return demoLaunch;
	}

	public void setDemoLaunch(String demoLaunch) {
		this.demoLaunch = demoLaunch;
	}

	/** default constructor */
	public ResCourse() {
	}

	/** minimal constructor */
	
	public ResCourse(String id,String CName,Double CPrice,String CNo){
		this.id = id;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CNo = CNo;
	}
	public ResCourse(String id,String CName,Double CPrice,String CNo,Long CDuration){
		this.id = id;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CNo = CNo;
		this.CDuration = CDuration;
	}
	public ResCourse(String id,String CName,Double CPrice,String CNo,Long CCredithour,String codeNo,String codeName){
		this.id = id;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CNo = CNo;
		this.CCredithour = CCredithour;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		code.setCodeName(codeName);
		this.sysCode = code;
	}
	public ResCourse(String id,String CName,Double CPrice,String CNo,Long CCredithour,String codeNo,String codeName,String CYear){
		this.id = id;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CNo = CNo;
		this.CCredithour = CCredithour;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		code.setCodeName(codeName);
		this.sysCode = code;
		this.CYear = CYear;
	}
	public ResCourse(String id,String CName,Double CPrice,String CNo,Long CCredithour,String codeNo,String codeName,String CYear,String CImage,String teacherName){
		this.id = id;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CNo = CNo;
		this.CCredithour = CCredithour;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		code.setCodeName(codeName);
		this.sysCode = code;
		this.CYear = CYear;
		this.CImage=CImage;
		SysTeacher sysTeacher = new SysTeacher();
		sysTeacher.setRealname(teacherName);
		this.sysTeacher = sysTeacher;
	}
	public ResCourse(String id,String CNo,String CName,String CReleaseFlag,Long COrdernum,String codeid,String codeNo){
		this.id = id;
		this.CNo = CNo;
		this.CName = CName;
		this.CReleaseFlag = CReleaseFlag;
		this.COrdernum = COrdernum;
		SysCode code = new SysCode();
		code.setId(codeid);
		code.setCodeNo(codeNo);
		this.sysCode = code;
		
	}
	
	public ResCourse(String id,String CNo,String CName,Double CPrice,Long CCredithour,String CReleaseFlag,Long COrdernum,String codeid,String codeNo){
		this.id = id;
		this.CNo = CNo;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CCredithour = CCredithour;
		this.CReleaseFlag = CReleaseFlag;
		this.COrdernum = COrdernum;
		SysCode code = new SysCode();
		code.setId(codeid);
		code.setCodeNo(codeNo);
		this.sysCode = code;
		
	}
	
	public ResCourse(String id,String CName,Double CPrice,Long CCredithour,String CImage,String CRecommend){
		this.id = id;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CCredithour = CCredithour;
		this.CImage = CImage;
		this.CRecommend = CRecommend;
	}
	public ResCourse(String id,String CNo,String CName,Double CPrice,Double CPeriod,Long CCredithour,String CImage,String CRecommend,String teacherid,String teacherName,String CDesc){
		this.id = id;
		this.CNo = CNo;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CPeriod = CPeriod;
		this.CCredithour = CCredithour;
		this.CImage = CImage;
		this.CRecommend = CRecommend;
		SysTeacher sysTeacher = new SysTeacher();
		sysTeacher.setId(teacherid);
		sysTeacher.setRealname(teacherName);
		this.sysTeacher = sysTeacher;
		this.CDesc=CDesc;
	}
	
	public ResCourse(String id,String CNo,String CName,Double CPrice,Double CPeriod,Long CCredithour,String CImage,String CRecommend,String teacherid,String teacherName,String CDesc,String codeAlias){
		this.id = id;
		this.CNo = CNo;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CPeriod = CPeriod;
		this.CCredithour = CCredithour;
		this.CImage = CImage;
		this.CRecommend = CRecommend;
		SysTeacher sysTeacher = new SysTeacher();
		sysTeacher.setId(teacherid);
		sysTeacher.setRealname(teacherName);
		this.sysTeacher = sysTeacher;
		SysCode code = new SysCode();
		code.setCodeAlias(codeAlias);
		this.sysCode = code;
		this.CDesc=CDesc;
	}
	
	public ResCourse(String id,String CNo,String CName,Double CPrice,Double CPeriod,Long CCredithour,String CImage,String CRecommend,String teacherid,String teacherName,String CDesc,String codeNo,String codeName){
		this.id = id;
		this.CNo = CNo;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CPeriod = CPeriod;
		this.CCredithour = CCredithour;
		this.CImage = CImage;
		this.CRecommend = CRecommend;
		SysTeacher sysTeacher = new SysTeacher();
		sysTeacher.setId(teacherid);
		sysTeacher.setRealname(teacherName);
		this.sysTeacher = sysTeacher;
		this.CDesc=CDesc;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		code.setCodeName(codeName);
		this.sysCode = code;
	}
	public ResCourse(String id,String CNo,String CName,Double CPrice,Double CPeriod,Long CCredithour,String CImage,String CRecommend,String teacherid,String teacherName,String CDesc,String codeNo,String codeName,String codeAlias){
		this.id = id;
		this.CNo = CNo;
		this.CName = CName;
		this.CPrice = CPrice;
		this.CPeriod = CPeriod;
		this.CCredithour = CCredithour;
		this.CImage = CImage;
		this.CRecommend = CRecommend;
		SysTeacher sysTeacher = new SysTeacher();
		sysTeacher.setId(teacherid);
		sysTeacher.setRealname(teacherName);
		this.sysTeacher = sysTeacher;
		this.CDesc=CDesc;
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		code.setCodeName(codeName);
		code.setCodeAlias(codeAlias);
		this.sysCode = code;
	}
	public ResCourse(String id,String CName,Long CCredithour,List teacherList){
		this.CCredithour = CCredithour;
		this.CName = CName;
		this.id = id;
		this.teacherList=teacherList;
	}
	
	public ResCourse(Double CPeriod, Long CCredithour, String CType,
			Long CChooseCount, String CReleaseFlag, String delflag) {
		this.CPeriod = CPeriod;
		this.CCredithour = CCredithour;
		this.CType = CType;
		this.CChooseCount = CChooseCount;
		this.CReleaseFlag = CReleaseFlag;
		this.delflag = delflag;
	}

	/** full constructor */
	public ResCourse(SysCode sysCode, String cwId, String CNo,
			String CName, String CDesc, String CMode, String CStarttime,
			String CEndtime, Double CPeriod, Long CCredithour, Long CDuration,
			Double CCost, Double CPrice, String CType, String CImage,
			Long CChooseCount, Long COrdernum, String CReleaseFlag,
			String CRecommend, String creator, String lasteditor,
			String createtime, String lastedittime, String delflag) {
		this.sysCode = sysCode;
		this.CNo = CNo;
		this.CName = CName;
		this.CDesc = CDesc;
		this.CMode = CMode;
		this.CStarttime = CStarttime;
		this.CEndtime = CEndtime;
		this.CPeriod = CPeriod;
		this.CCredithour = CCredithour;
		this.CDuration = CDuration;
		this.CCost = CCost;
		this.CPrice = CPrice;
		this.CType = CType;
		this.CImage = CImage;
		this.CChooseCount = CChooseCount;
		this.COrdernum = COrdernum;
		this.CReleaseFlag = CReleaseFlag;
		this.CRecommend = CRecommend;
		this.creator = creator;
		this.lasteditor = lasteditor;
		this.createtime = createtime;
		this.lastedittime = lastedittime;
		this.delflag = delflag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SysCode getSysCode() {
		return this.sysCode;
	}

	public void setSysCode(SysCode sysCode) {
		this.sysCode = sysCode;
	}

	public ResCourseware getResCourseware() {
		return resCourseware;
	}

	public void setResCourseware(ResCourseware resCourseware) {
		this.resCourseware = resCourseware;
	}

	public String getCNo() {
		return this.CNo;
	}

	public void setCNo(String CNo) {
		this.CNo = CNo;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public String getCDesc() {
		return this.CDesc;
	}

	public void setCDesc(String CDesc) {
		this.CDesc = CDesc;
	}

	public String getCMode() {
		return this.CMode;
	}

	public void setCMode(String CMode) {
		this.CMode = CMode;
	}

	public String getCStarttime() {
		return this.CStarttime;
	}

	public void setCStarttime(String CStarttime) {
		this.CStarttime = CStarttime;
	}

	public String getCEndtime() {
		return this.CEndtime;
	}

	public void setCEndtime(String CEndtime) {
		this.CEndtime = CEndtime;
	}


	public Double getCPeriod() {
		return CPeriod;
	}

	public void setCPeriod(Double period) {
		CPeriod = period;
	}

	public Long getCCredithour() {
		return this.CCredithour;
	}

	public void setCCredithour(Long CCredithour) {
		this.CCredithour = CCredithour;
	}

	public Long getCDuration() {
		return this.CDuration;
	}

	public void setCDuration(Long CDuration) {
		this.CDuration = CDuration;
	}

	public Double getCCost() {
		return this.CCost;
	}

	public void setCCost(Double CCost) {
		this.CCost = CCost;
	}

	public Double getCPrice() {
		return this.CPrice;
	}

	public void setCPrice(Double CPrice) {
		this.CPrice = CPrice;
	}

	public String getCType() {
		return this.CType;
	}

	public void setCType(String CType) {
		this.CType = CType;
	}

	public String getCImage() {
		return this.CImage;
	}

	public void setCImage(String CImage) {
		this.CImage = CImage;
	}

	public Long getCChooseCount() {
		return this.CChooseCount;
	}

	public void setCChooseCount(Long CChooseCount) {
		this.CChooseCount = CChooseCount;
	}

	public Long getCOrdernum() {
		return this.COrdernum;
	}

	public void setCOrdernum(Long COrdernum) {
		this.COrdernum = COrdernum;
	}

	public String getCReleaseFlag() {
		return this.CReleaseFlag;
	}

	public void setCReleaseFlag(String CReleaseFlag) {
		this.CReleaseFlag = CReleaseFlag;
	}

	public String getCRecommend() {
		return this.CRecommend;
	}

	public void setCRecommend(String CRecommend) {
		this.CRecommend = CRecommend;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getLasteditor() {
		return this.lasteditor;
	}

	public void setLasteditor(String lasteditor) {
		this.lasteditor = lasteditor;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getLastedittime() {
		return this.lastedittime;
	}

	public void setLastedittime(String lastedittime) {
		this.lastedittime = lastedittime;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public List getTeacherList() {
		return teacherList;
	}

	public void setTeacherList(List teacherList) {
		this.teacherList = teacherList;
	}

	public SysTeacher getSysTeacher() {
		return sysTeacher;
	}
	public void setSysTeacher(SysTeacher sysTeacher) {
		this.sysTeacher = sysTeacher;
	}
	public double getAvgEva() {
		return avgEva;
	}

	public void setAvgEva(double avgEva) {
		this.avgEva = avgEva;
	}
	public class CwComparatorByNo implements Comparator{
	    public int compare(Object o1,Object o2){
	    	ResCouCw c1=(ResCouCw)o1;
	    	ResCouCw c2=(ResCouCw)o2;
	        if(c1.getResCourseware().getCwNo().compareTo(c2.getResCourseware().getCwNo())>=0)
	      	  return 1;
	        if(c1.getResCourseware().getCwNo().compareTo(c2.getResCourseware().getCwNo())<0)
	      	  return -1;
	        return 0;
	    }
	}

	public void setCwList(List cwList) {
		this.cwList = cwList;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}
	public String getIsExam() {
		return isExam;
	}
	public void setIsExam(String isExam) {
		this.isExam = isExam;
	}
	public List getBookList() {
		return bookList;
	}
	
	public void setBookList(List bookList) {
		this.bookList = bookList;
	}
	public String getCYear() {
		return CYear;
	}
	public void setCYear(String year) {
		CYear = year;
	}
	public Long getGoodNum() {
		return goodNum;
	}
	public void setGoodNum(Long goodNum) {
		this.goodNum = goodNum;
	}
	public Long getStudyNum() {
		return studyNum;
	}
	public void setStudyNum(Long studyNum) {
		this.studyNum = studyNum;
	}
	public String getIsHot() {
		return isHot;
	}
	public void setIsHot(String isHot) {
		this.isHot = isHot;
	}
	public String getIsAudition() {
		return isAudition;
	}
	public void setIsAudition(String isAudition) {
		this.isAudition = isAudition;
	}
	public String getIsShopping() {
		return isShopping;
	}
	public void setIsShopping(String isShopping) {
		this.isShopping = isShopping;
	}
	public String getClassNo() {
		return classNo;
	}
	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}
}