package cn.gc80.datamodel.res;

import java.util.HashSet;
import java.util.Set;

import cn.gc80.datamodel.sysbase.SysCode;

/**
 * YfssResCourseware generated by MyEclipse Persistence Tools
 */

public class ResCourseware implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2504806959269121616L;

	private String id;

	private SysCode sysCode;

	private ResResinfo resResinfo;

	private String cwNo;

	private String cwName;

	private String cwDesc;

	private String cwVersion;

	private String cwReleaseFlag;

	private String cwReleaseDir;

	private String cwIndexFile;

	private Long cwPeriod;

	private Double cwSize;

	private String cwScorm;
	
	private String trackMode;

	private String cwFileserver;

	private String isdemo;

	private String cwShowUrl;

	private String shareChapter;

	private String lasteditor;

	private String creator;

	private String createtime;

	private String lastedittime;

	private String delflag;
	
	private Long creditnum;
	
	private Long cwAllowAttempt;

	private Set trainTeachCourses = new HashSet(0);
	private long questionCount;

	// Constructors

	public long getQuestionCount() {
		return questionCount;
	}

	public void setQuestionCount(long questionCount) {
		this.questionCount = questionCount;
	}

	/** default constructor */
	public ResCourseware() {
	}

	/** minimal constructor */
	public ResCourseware(ResResinfo resResinfo, String cwName,
			String cwReleaseFlag, String cwScorm, String delflag) {
		this.resResinfo = resResinfo;
		this.cwName = cwName;
		this.cwReleaseFlag = cwReleaseFlag;
		this.cwScorm = cwScorm;
		this.delflag = delflag;
	}

	
	public ResCourseware(String id,String cwNo,String cwFileserver,String cwScorm,String cwReleaseDir,String cwIndexFile,Long creditnum,Long cwPeriod,String trackMode,String cwName){
		this.id = id;
		this.cwNo = cwNo;
		this.cwFileserver = cwFileserver;
		this.cwScorm = cwScorm;
		this.cwReleaseDir  = cwReleaseDir;
		this.cwIndexFile = cwIndexFile;
		this.creditnum = creditnum;
		this.cwPeriod = cwPeriod;
		this.trackMode = trackMode;	
		this.cwName = cwName;
	}
	
	public ResCourseware(String id,String cwName){
		this.id = id;
		this.cwName = cwName;
	}
	/** full constructor */
	public ResCourseware(SysCode sysCode,
			ResResinfo resResinfo, String cwNo, String cwName,
			String cwDesc, String cwVersion, String cwReleaseFlag,
			String cwReleaseDir, String cwIndexFile, Long cwPeriod,
			Double cwSize, String cwScorm, String cwFileserver, String isdemo,
			String cwShowUrl, String shareChapter, String lasteditor,
			String creator, String createtime, String lastedittime,
			String delflag) {
		this.sysCode = sysCode;
		this.resResinfo = resResinfo;
		this.cwNo = cwNo;
		this.cwName = cwName;
		this.cwDesc = cwDesc;
		this.cwVersion = cwVersion;
		this.cwReleaseFlag = cwReleaseFlag;
		this.cwReleaseDir = cwReleaseDir;
		this.cwIndexFile = cwIndexFile;
		this.cwPeriod = cwPeriod;
		this.cwSize = cwSize;
		this.cwScorm = cwScorm;
		this.cwFileserver = cwFileserver;
		this.isdemo = isdemo;
		this.cwShowUrl = cwShowUrl;
		this.shareChapter = shareChapter;
		this.lasteditor = lasteditor;
		this.creator = creator;
		this.createtime = createtime;
		this.lastedittime = lastedittime;
		this.delflag = delflag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCwNo() {
		return this.cwNo;
	}

	public void setCwNo(String cwNo) {
		this.cwNo = cwNo;
	}

	public String getCwName() {
		return this.cwName;
	}

	public void setCwName(String cwName) {
		this.cwName = cwName;
	}

	public String getCwDesc() {
		return this.cwDesc;
	}

	public void setCwDesc(String cwDesc) {
		this.cwDesc = cwDesc;
	}

	public String getCwVersion() {
		return this.cwVersion;
	}

	public void setCwVersion(String cwVersion) {
		this.cwVersion = cwVersion;
	}

	public String getCwReleaseFlag() {
		return this.cwReleaseFlag;
	}

	public void setCwReleaseFlag(String cwReleaseFlag) {
		this.cwReleaseFlag = cwReleaseFlag;
	}

	public String getCwReleaseDir() {
		return this.cwReleaseDir;
	}

	public void setCwReleaseDir(String cwReleaseDir) {
		this.cwReleaseDir = cwReleaseDir;
	}

	public String getCwIndexFile() {
		return this.cwIndexFile;
	}

	public void setCwIndexFile(String cwIndexFile) {
		this.cwIndexFile = cwIndexFile;
	}

	public Long getCwPeriod() {
		return cwPeriod;
	}

	public void setCwPeriod(Long cwPeriod) {
		this.cwPeriod = cwPeriod;
	}

	public Double getCwSize() {
		return this.cwSize;
	}

	public void setCwSize(Double cwSize) {
		this.cwSize = cwSize;
	}

	public String getCwScorm() {
		return this.cwScorm;
	}

	public void setCwScorm(String cwScorm) {
		this.cwScorm = cwScorm;
	}

	public String getCwFileserver() {
		return this.cwFileserver;
	}

	public void setCwFileserver(String cwFileserver) {
		this.cwFileserver = cwFileserver;
	}

	public String getIsdemo() {
		return this.isdemo;
	}

	public void setIsdemo(String isdemo) {
		this.isdemo = isdemo;
	}

	public String getCwShowUrl() {
		return this.cwShowUrl;
	}

	public void setCwShowUrl(String cwShowUrl) {
		this.cwShowUrl = cwShowUrl;
	}

	public String getShareChapter() {
		return this.shareChapter;
	}

	public void setShareChapter(String shareChapter) {
		this.shareChapter = shareChapter;
	}

	public String getLasteditor() {
		return this.lasteditor;
	}

	public void setLasteditor(String lasteditor) {
		this.lasteditor = lasteditor;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getLastedittime() {
		return this.lastedittime;
	}

	public void setLastedittime(String lastedittime) {
		this.lastedittime = lastedittime;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}


	public ResResinfo getResResinfo() {
		return resResinfo;
	}

	public void setResResinfo(ResResinfo resResinfo) {
		this.resResinfo = resResinfo;
	}

	public SysCode getSysCode() {
		return sysCode;
	}

	public void setSysCode(SysCode sysCode) {
		this.sysCode = sysCode;
	}

	public Long getCreditnum() {
		return creditnum;
	}

	public void setCreditnum(Long creditnum) {
		this.creditnum = creditnum;
	}

	public Set getTrainTeachCourses() {
		return trainTeachCourses;
	}

	public void setTrainTeachCourses(Set trainTeachCourses) {
		this.trainTeachCourses = trainTeachCourses;
	}

	public String getTrackMode() {
		return trackMode;
	}

	public void setTrackMode(String trackMode) {
		this.trackMode = trackMode;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getCwAllowAttempt() {
		return cwAllowAttempt;
	}

	public void setCwAllowAttempt(Long cwAllowAttempt) {
		this.cwAllowAttempt = cwAllowAttempt;
	}

}