package cn.gc80.datamodel.res;

import java.util.Set;

import cn.gc80.datamodel.sysbase.SysCode;

/**
 * YfssResResinfo generated by MyEclipse Persistence Tools
 */

public class ResResinfo implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -2948490176675864597L;

	private String id;

	private SysCode sysCode;

	private String resParent;

	private String resIdentifier;

	private String resName;

	private String resFormat;

	private String resUrl;

	private String resDesc;

	private String resAuthor;

	private String createtime;

	private String lastedittime;

	private String creator;

	private String lasteditor;

	private String delflag;
	
	private Long resSize;


	// Constructors

	/** default constructor */
	public ResResinfo() {
	}

	/** minimal constructor */
	public ResResinfo(String resName, String resUrl, String delflag) {
		this.resName = resName;
		this.resUrl = resUrl;
		this.delflag = delflag;
	}

	/** full constructor */
	public ResResinfo(SysCode sysCode, String resParent,
			String resIdentifier, String resName, String resFormat,
			String resUrl, String resDesc, String resAuthor, String createtime,
			String lastedittime, String creator, String lasteditor,
			String delflag, Set yfssResQueMatchAnswers,
			Set yfssResMatchOptions, Set yfssResQueOptions,
			Set yfssResCoursewares, Set yfssResPapers, Set yfssResQuestions,
			Set yfssResChapters, Set yfssResCouReses) {
		this.sysCode = sysCode;
		this.resParent = resParent;
		this.resIdentifier = resIdentifier;
		this.resName = resName;
		this.resFormat = resFormat;
		this.resUrl = resUrl;
		this.resDesc = resDesc;
		this.resAuthor = resAuthor;
		this.createtime = createtime;
		this.lastedittime = lastedittime;
		this.creator = creator;
		this.lasteditor = lasteditor;
		this.delflag = delflag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getResParent() {
		return this.resParent;
	}

	public void setResParent(String resParent) {
		this.resParent = resParent;
	}

	public String getResIdentifier() {
		return this.resIdentifier;
	}

	public void setResIdentifier(String resIdentifier) {
		this.resIdentifier = resIdentifier;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public String getResFormat() {
		return this.resFormat;
	}

	public void setResFormat(String resFormat) {
		this.resFormat = resFormat;
	}

	public String getResUrl() {
		return this.resUrl;
	}

	public void setResUrl(String resUrl) {
		this.resUrl = resUrl;
	}

	public String getResDesc() {
		return this.resDesc;
	}

	public void setResDesc(String resDesc) {
		this.resDesc = resDesc;
	}

	public String getResAuthor() {
		return this.resAuthor;
	}

	public void setResAuthor(String resAuthor) {
		this.resAuthor = resAuthor;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getLastedittime() {
		return this.lastedittime;
	}

	public void setLastedittime(String lastedittime) {
		this.lastedittime = lastedittime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getLasteditor() {
		return this.lasteditor;
	}

	public void setLasteditor(String lasteditor) {
		this.lasteditor = lasteditor;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public Long getResSize() {
		return resSize;
	}

	public void setResSize(Long resSize) {
		this.resSize = resSize;
	}

	public SysCode getSysCode() {
		return sysCode;
	}

	public void setSysCode(SysCode sysCode) {
		this.sysCode = sysCode;
	}

}