package cn.gc80.datamodel.exam;

import cn.gc80.datamodel.res.ResResinfo;

/**
 * ResMatchOption generated by MyEclipse Persistence Tools
 */

public class ExamMatchOption implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -224064618147541648L;

	private String id;

	private ResResinfo resResinfo;

	private ExamQuestion examQuestion;

	private ExamQueMatchAnswer examQueMatchAnswer;

	private String opContent;

	// Constructors

	/** default constructor */
	public ExamMatchOption() {
	}

	/** minimal constructor */
	public ExamMatchOption(ExamQuestion examQuestion, String opContent) {
		this.examQuestion = examQuestion;
		this.opContent = opContent;
	}

	/** full constructor */
	public ExamMatchOption(ResResinfo resResinfo,
			ExamQuestion examQuestion,
			ExamQueMatchAnswer examQueMatchAnswer, String opContent) {
		this.resResinfo = resResinfo;
		this.examQuestion = examQuestion;
		this.examQueMatchAnswer = examQueMatchAnswer;
		this.opContent = opContent;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public ResResinfo getResResinfo() {
		return this.resResinfo;
	}

	public void setResResinfo(ResResinfo resResinfo) {
		this.resResinfo = resResinfo;
	}

	public ExamQueMatchAnswer getExamQueMatchAnswer() {
		return examQueMatchAnswer;
	}

	public void setExamQueMatchAnswer(ExamQueMatchAnswer examQueMatchAnswer) {
		this.examQueMatchAnswer = examQueMatchAnswer;
	}

	public ExamQuestion getExamQuestion() {
		return examQuestion;
	}

	public void setExamQuestion(ExamQuestion examQuestion) {
		this.examQuestion = examQuestion;
	}

	public String getOpContent() {
		return this.opContent;
	}

	public void setOpContent(String opContent) {
		this.opContent = opContent;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

}