package cn.gc80.datamodel.exam;

import cn.gc80.datamodel.res.ResCourse;
import cn.gc80.datamodel.res.ResCourseware;
import cn.gc80.datamodel.sysbase.SysUser;

/**
 * ExamUserQuiz generated by MyEclipse Persistence Tools
 */

public class ExamUserQuiz implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -6037744015677371166L;

	private String id;

	private SysUser sysUser;

	private ExamQuiz examQuiz;

	private ExamPaper examPaper;

	private Long sequence;

	private String starttime;

	private String finishtime;

	private Long usedtime;

	private Double grade;

	private String status;

	private String postil;

	private String reador;

	private String readTime;

	// Constructors

	/** default constructor */
	public ExamUserQuiz() {
	}

	public ExamUserQuiz(String id,String userid ,String userName,String realname,String quizid,String quizName,String paperid,String paperName,String courseid,String CName,String coursewareid,String cwName,Long creditnum,Double grade,String starttime,String finishtime){
		this.id = id;
		SysUser user = new SysUser();
		user.setId(userid);
		user.setUserName(userName);
		user.setRealname(realname);
		this.sysUser = user;
		ExamQuiz quiz = new ExamQuiz();
		quiz.setId(quizid);
		quiz.setName(quizName);
		this.examQuiz = quiz;
		ExamPaper paper = new ExamPaper();
		paper.setId(paperid);
		paper.setName(paperName);
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		paper.setResCourse(course);
		ResCourseware courseware = new ResCourseware();
		courseware.setId(coursewareid);
		courseware.setCwName(cwName);
		courseware.setCreditnum(creditnum);
		paper.setResCourseware(courseware);
		this.examPaper = paper;
		this.grade = grade;
		this.starttime = starttime;
		this.finishtime = finishtime;
	}
	
	public ExamUserQuiz(String id,String userId,String quizId,String quizName,String paperId,Double grade){
		this.id = id;
		SysUser sysUser = new SysUser();
		sysUser.setId(userId);
		this.sysUser = sysUser;
		ExamQuiz examQuiz = new ExamQuiz();
		examQuiz.setId(quizId);
		examQuiz.setName(quizName);
		this.examQuiz = examQuiz;
		ExamPaper paper = new ExamPaper();
		paper.setId(paperId);
		this.examPaper = paper;
		this.grade = grade;
		
	}
	
	/** minimal constructor */
	public ExamUserQuiz(SysUser sysUser, ExamQuiz examQuiz,
			ExamPaper resPaper, Long sequence, String starttime,
			String finishtime, Double grade, String status) {
		this.sysUser = sysUser;
		this.examQuiz = examQuiz;
		this.examPaper = resPaper;
		this.sequence = sequence;
		this.starttime = starttime;
		this.finishtime = finishtime;
		this.grade = grade;
		this.status = status;
	}

	/** full constructor */
	public ExamUserQuiz(SysUser sysUser, ExamQuiz examQuiz,
			ExamPaper resPaper, Long sequence, String starttime,
			String finishtime, Long usedtime, Double grade, String status,
			String postil, String reador, String readTime) {
		this.sysUser = sysUser;
		this.examQuiz = examQuiz;
		this.examPaper = resPaper;
		this.sequence = sequence;
		this.starttime = starttime;
		this.finishtime = finishtime;
		this.usedtime = usedtime;
		this.grade = grade;
		this.status = status;
		this.postil = postil;
		this.reador = reador;
		this.readTime = readTime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public Long getSequence() {
		return this.sequence;
	}

	public void setSequence(Long sequence) {
		this.sequence = sequence;
	}

	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getFinishtime() {
		return this.finishtime;
	}

	public void setFinishtime(String finishtime) {
		this.finishtime = finishtime;
	}

	public Long getUsedtime() {
		return this.usedtime;
	}

	public void setUsedtime(Long usedtime) {
		this.usedtime = usedtime;
	}

	public Double getGrade() {
		return this.grade;
	}

	public void setGrade(Double grade) {
		this.grade = grade;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPostil() {
		return this.postil;
	}

	public void setPostil(String postil) {
		this.postil = postil;
	}

	public String getReador() {
		return this.reador;
	}

	public void setReador(String reador) {
		this.reador = reador;
	}

	public String getReadTime() {
		return this.readTime;
	}

	public void setReadTime(String readTime) {
		this.readTime = readTime;
	}

	public ExamQuiz getExamQuiz() {
		return examQuiz;
	}

	public void setExamQuiz(ExamQuiz examQuiz) {
		this.examQuiz = examQuiz;
	}

	public ExamPaper getExamPaper() {
		return examPaper;
	}

	public void setExamPaper(ExamPaper examPaper) {
		this.examPaper = examPaper;
	}

	public SysUser getSysUser() {
		return sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

}