package cn.gc80.datamodel.exam;

import java.text.SimpleDateFormat;
import java.util.Date;

import cn.gc80.datamodel.res.ResCourse;
import cn.gc80.datamodel.res.ResCourseware;
import cn.gc80.datamodel.sysbase.SysCode;
import cn.gc80.datamodel.training.TrainProject;

/**
 * YfssExamQuiz generated by MyEclipse Persistence Tools
 */

public class ExamQuiz implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -6365344096088296892L;

	private String id;

	private ResCourse resCourse;
	
	private TrainProject trainProject;
	
	private ResCourseware resCourseware;

	private SysCode sysCode;

	private String paperids;

	private String name;

	private String description;

	private String timeopen;

	private String timeclose;

	private Long timelimit;

	private Long credit;

	private String randomquestion;

	private Long maxallowed;

	private String attemptonlast;

	private String grademethod;

	private String password;

	private Double passscore;

	private String isScore;

	private String quizType;

	private String buildType;

	private String status;

	private String showAnswer;

	private String showScore;

	private String paperXmlcontent;

	private String createtime;

	private String lastedittime;

	private String creator;

	private String lasteditor;

	private String delfalg;

	private boolean expire;
	
	private String certType;
	// Constructors

	public String getCertType() {
		return certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	/** default constructor */
	public ExamQuiz() {
	}

	public ExamQuiz(String id,String paperids,String name,Long timelimit) {
		this.id = id;
		this.paperids = paperids;
		this.name = name;
		this.timelimit = timelimit;
	}
	public ExamQuiz(String id,String name,Long timelimit) {
		this.id = id;
		this.name = name;
		this.timelimit = timelimit;
	}
	/** minimal constructor */
	public ExamQuiz( String paperids,
			String name, Long timelimit, Long credit, String randomquestion,
			String attemptonlast, String grademethod, String isScore,
			String quizType, String buildType, String status,
			String showAnswer, String showScore, String delfalg) {
		this.paperids = paperids;
		this.name = name;
		this.timelimit = timelimit;
		this.credit = credit;
		this.randomquestion = randomquestion;
		this.attemptonlast = attemptonlast;
		this.grademethod = grademethod;
		this.isScore = isScore;
		this.quizType = quizType;
		this.buildType = buildType;
		this.status = status;
		this.showAnswer = showAnswer;
		this.showScore = showScore;
		this.delfalg = delfalg;
	}

	/** full constructor */
	public ExamQuiz(ResCourse resCourse, SysCode sysCode,
			String paperids, String name, String description, String timeopen,
			String timeclose, Long timelimit, Long credit,
			String randomquestion, Long maxallowed, String attemptonlast,
			String grademethod, String password, Double passscore,
			String isScore, String quizType, String buildType, String status,
			String showAnswer, String showScore, String paperXmlcontent,
			String createtime, String lastedittime, String creator,
			String lasteditor, String delfalg) {
		this.resCourse = resCourse;
		this.sysCode = sysCode;
		this.paperids = paperids;
		this.name = name;
		this.description = description;
		this.timeopen = timeopen;
		this.timeclose = timeclose;
		this.timelimit = timelimit;
		this.credit = credit;
		this.randomquestion = randomquestion;
		this.maxallowed = maxallowed;
		this.attemptonlast = attemptonlast;
		this.grademethod = grademethod;
		this.password = password;
		this.passscore = passscore;
		this.isScore = isScore;
		this.quizType = quizType;
		this.buildType = buildType;
		this.status = status;
		this.showAnswer = showAnswer;
		this.showScore = showScore;
		this.paperXmlcontent = paperXmlcontent;
		this.createtime = createtime;
		this.lastedittime = lastedittime;
		this.creator = creator;
		this.lasteditor = lasteditor;
		this.delfalg = delfalg;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPaperids() {
		return this.paperids;
	}

	public void setPaperids(String paperids) {
		this.paperids = paperids;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTimeopen() {
		return this.timeopen;
	}

	public void setTimeopen(String timeopen) {
		this.timeopen = timeopen;
	}

	public String getTimeclose() {
		return this.timeclose;
	}

	public void setTimeclose(String timeclose) {
		this.timeclose = timeclose;
	}

	public Long getTimelimit() {
		return this.timelimit;
	}

	public void setTimelimit(Long timelimit) {
		this.timelimit = timelimit;
	}

	public Long getCredit() {
		return this.credit;
	}

	public void setCredit(Long credit) {
		this.credit = credit;
	}

	public String getRandomquestion() {
		return this.randomquestion;
	}

	public void setRandomquestion(String randomquestion) {
		this.randomquestion = randomquestion;
	}

	public Long getMaxallowed() {
		return this.maxallowed;
	}

	public void setMaxallowed(Long maxallowed) {
		this.maxallowed = maxallowed;
	}

	public String getAttemptonlast() {
		return this.attemptonlast;
	}

	public void setAttemptonlast(String attemptonlast) {
		this.attemptonlast = attemptonlast;
	}

	public String getGrademethod() {
		return this.grademethod;
	}

	public void setGrademethod(String grademethod) {
		this.grademethod = grademethod;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Double getPassscore() {
		return this.passscore;
	}

	public void setPassscore(Double passscore) {
		this.passscore = passscore;
	}

	public String getIsScore() {
		return this.isScore;
	}

	public void setIsScore(String isScore) {
		this.isScore = isScore;
	}

	public String getQuizType() {
		return this.quizType;
	}

	public void setQuizType(String quizType) {
		this.quizType = quizType;
	}

	public String getBuildType() {
		return this.buildType;
	}

	public void setBuildType(String buildType) {
		this.buildType = buildType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getShowAnswer() {
		return this.showAnswer;
	}

	public void setShowAnswer(String showAnswer) {
		this.showAnswer = showAnswer;
	}

	public String getShowScore() {
		return this.showScore;
	}

	public void setShowScore(String showScore) {
		this.showScore = showScore;
	}

	public String getPaperXmlcontent() {
		return this.paperXmlcontent;
	}

	public void setPaperXmlcontent(String paperXmlcontent) {
		this.paperXmlcontent = paperXmlcontent;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getLastedittime() {
		return this.lastedittime;
	}

	public void setLastedittime(String lastedittime) {
		this.lastedittime = lastedittime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getLasteditor() {
		return this.lasteditor;
	}

	public void setLasteditor(String lasteditor) {
		this.lasteditor = lasteditor;
	}

	public String getDelfalg() {
		return this.delfalg;
	}

	public void setDelfalg(String delfalg) {
		this.delfalg = delfalg;
	}

	public boolean isExpire() {
		try{
			 SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
	if(timeopen!=null&&!timeopen.equals("")){
		long timeopenl =sf.parse(timeopen).getTime();
		long timeoclose =sf.parse(timeclose).getTime();
		expire=true;
		if(new Date().getTime()>=timeopenl&&new Date().getTime()<=timeoclose){
			expire=false;
		}
	}else{
		expire=false;	
	}
		}catch(Exception e){
			e.printStackTrace();
		}
		return expire;
	}

	public ResCourse getResCourse() {
		return resCourse;
	}

	public void setResCourse(ResCourse resCourse) {
		this.resCourse = resCourse;
	}

	public ResCourseware getResCourseware() {
		return resCourseware;
	}

	public void setResCourseware(ResCourseware resCourseware) {
		this.resCourseware = resCourseware;
	}

	public SysCode getSysCode() {
		return sysCode;
	}

	public void setSysCode(SysCode sysCode) {
		this.sysCode = sysCode;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public void setExpire(boolean expire) {
		this.expire = expire;
	}

	public TrainProject getTrainProject() {
		return trainProject;
	}

	public void setTrainProject(TrainProject trainProject) {
		this.trainProject = trainProject;
	}

}