package cn.gc80.datamodel.sysbase;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * LrnSysAdmin generated by MyEclipse Persistence Tools
 */

public class SysAdmin implements java.io.Serializable {

	// Fields

	private String id;

	private String userName;

	private String userPasswd;

	private String realname;

	private String email;

	private String mobile;

	private String phone;

	private String areascope;

	private String status;

	private String delflag;
	
	private String spot;
	
	private String lockno;
	
	private Set sysUserRoles = new HashSet(0);
	
	private List spotList;

	// Constructors

	public Set getSysUserRoles() {
		return sysUserRoles;
	}

	public void setSysUserRoles(Set sysUserRoles) {
		this.sysUserRoles = sysUserRoles;
	}

	/** default constructor */
	public SysAdmin() {
	}

	/** minimal constructor */
	public SysAdmin(String userName, String userPasswd, String realname,
			String areascope, String status, String delflag) {
		this.userName = userName;
		this.userPasswd = userPasswd;
		this.realname = realname;
		this.areascope = areascope;
		this.status = status;
		this.delflag = delflag;
	}

	/** full constructor */
	public SysAdmin(String userName, String userPasswd, String realname,
			String email, String mobile, String phone, String areascope,
			String status, String delflag) {
		this.userName = userName;
		this.userPasswd = userPasswd;
		this.realname = realname;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.areascope = areascope;
		this.status = status;
		this.delflag = delflag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPasswd() {
		return this.userPasswd;
	}

	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAreascope() {
		return this.areascope;
	}

	public void setAreascope(String areascope) {
		this.areascope = areascope;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public String getSpot() {
		return spot;
	}

	public void setSpot(String spot) {
		this.spot = spot;
	}

	public String getLockno() {
		return lockno;
	}

	public void setLockno(String lockno) {
		this.lockno = lockno;
	}

	public List getSpotList() {
		return spotList;
	}

	public void setSpotList(List spotList) {
		this.spotList = spotList;
	}

}