package cn.gc80.datamodel.sysbase;

/**
 * YfssSysCard generated by MyEclipse Persistence Tools
 */

public class SysCard implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 6608921017455721495L;

	private String id;

	private SysCardTemplate sysCardTemplate;
	
	private SysUser sysUser;

	private String cardNo;

	private String cardPassword;

	private String cardStatus;

	private String cardSoldTime;

	private String creator;

	private String createtime;

	private String delfalg;

	private Double cardBalance;
	
	private Long cardLimit;
	
	private Long cardAttempt;
	
	private Long amount;
	// Constructors

	/** default constructor */
	public SysCard() {
	}

	/** minimal constructor */
	public SysCard(SysCardTemplate sysCardTemplate, String cardNo,
			String cardPassword, Long cardCost, Long cardPrice,
			String cardStatus, String creator, String lasteditor,
			String createtime, String lastedittime, String delfalg) {
		this.sysCardTemplate = sysCardTemplate;
		this.cardNo = cardNo;
		this.cardPassword = cardPassword;
		this.cardStatus = cardStatus;
		this.creator = creator;
		this.createtime = createtime;
		this.delfalg = delfalg;
	}

	/** full constructor */
	public SysCard(SysCardTemplate sysCardTemplate, String cardNo,
			String cardPassword, Long cardCost, Long cardPrice,
			String cardStatus, String cardSoldTime, String cardUseTime,
			String creator, String lasteditor, String createtime,
			String lastedittime, String delfalg) {
		this.sysCardTemplate = sysCardTemplate;
		this.cardNo = cardNo;
		this.cardPassword = cardPassword;
		this.cardStatus = cardStatus;
		this.cardSoldTime = cardSoldTime;
		this.creator = creator;
		this.createtime = createtime;
		this.delfalg = delfalg;
	}
	public SysCard( String id, String cardNo, String cardPassword, 
			Long tempDenomination,Long price, String tempName, String tempValidate, Double cardBalance){
		this.id = id;
		this.cardPassword = cardPassword;
		this.cardNo = cardNo;
		this.cardBalance = cardBalance;
		SysCardTemplate systemplate=new SysCardTemplate();
		systemplate.setTempDenomination(tempDenomination);
		systemplate.setPrice(price);
		systemplate.setTempName(tempName);
		systemplate.setTempValidate(tempValidate);
		this.sysCardTemplate = systemplate;
		
	}
	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getCardPassword() {
		return this.cardPassword;
	}

	public void setCardPassword(String cardPassword) {
		this.cardPassword = cardPassword;
	}

	public String getCardStatus() {
		return this.cardStatus;
	}

	public void setCardStatus(String cardStatus) {
		this.cardStatus = cardStatus;
	}

	public String getCardSoldTime() {
		return this.cardSoldTime;
	}

	public void setCardSoldTime(String cardSoldTime) {
		this.cardSoldTime = cardSoldTime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}


	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}


	public String getDelfalg() {
		return this.delfalg;
	}

	public void setDelfalg(String delfalg) {
		this.delfalg = delfalg;
	}

	public Long getAmount() {
		return amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public Double getCardBalance() {
		return cardBalance;
	}

	public void setCardBalance(Double cardBalance) {
		this.cardBalance = cardBalance;
	}

	public SysCardTemplate getSysCardTemplate() {
		return sysCardTemplate;
	}

	public void setSysCardTemplate(SysCardTemplate sysCardTemplate) {
		this.sysCardTemplate = sysCardTemplate;
	}

	public SysUser getSysUser() {
		return sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public Long getCardLimit() {
		return cardLimit;
	}

	public void setCardLimit(Long cardLimit) {
		this.cardLimit = cardLimit;
	}

	public Long getCardAttempt() {
		return cardAttempt;
	}

	public void setCardAttempt(Long cardAttempt) {
		this.cardAttempt = cardAttempt;
	}

}