package cn.gc80.datamodel.sysbase;

import java.util.List;

/**
 * SysProvince generated by MyEclipse Persistence Tools
 */

public class SysProvince  implements java.io.Serializable {

	private static final long serialVersionUID = 8920022644447632835L;
	private String codeid;
    private SysProvince sysProvince;
    private String cityname;
    private List spotList;

    // Constructors

    /** default constructor */
    public SysProvince() {
    }

	/** minimal constructor */
    public SysProvince(String codeid,String parentid, String cityname) {
        this.codeid = codeid;
        SysProvince prov = new SysProvince();
        prov.setCodeid(parentid);
        this.setSysProvince(prov);
        this.cityname = cityname;
    }
   
    public SysProvince(String codeid, String cityname) {
        this.codeid = codeid;
        this.cityname = cityname;
    }
   
    // Property accessors

    public String getCodeid() {
        return this.codeid;
    }
    
    public void setCodeid(String codeid) {
        this.codeid = codeid;
    }

    public SysProvince getSysProvince() {
		return sysProvince;
	}

	public void setSysProvince(SysProvince sysProvince) {
		this.sysProvince = sysProvince;
	}

	public String getCityname() {
        return this.cityname;
    }
    
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

	public List getSpotList() {
		return spotList;
	}

	public void setSpotList(List spotList) {
		this.spotList = spotList;
	}
}