package cn.gc80.datamodel.sysbase;


/**
 * LrnSysTeacher generated by MyEclipse Persistence Tools
 */

public class SysTeacher implements java.io.Serializable {

	// Fields

	private String id;

	private String userName;

	private String userPasswd;

	private String realname;
	
	private String cardno;

	private String email;

	private String mobile;

	private String phone;

	private String photo;

	private String memo;

	private String status;

	private String delflag;

	// Constructors

	/** default constructor */
	public SysTeacher() {
	}

	/** minimal constructor */
	public SysTeacher(String userName, String userPasswd, String realname,
			String status, String delflag) {
		this.userName = userName;
		this.userPasswd = userPasswd;
		this.realname = realname;
		this.status = status;
		this.delflag = delflag;
	}

	/** full constructor */
	public SysTeacher(String userName, String userPasswd, String realname,
			String email, String mobile, String phone, String photo,
			String memo, String status, String delflag) {
		this.userName = userName;
		this.userPasswd = userPasswd;
		this.realname = realname;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.photo = photo;
		this.memo = memo;
		this.status = status;
		this.delflag = delflag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPasswd() {
		return this.userPasswd;
	}

	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public String getCardno() {
		return cardno;
	}

	public void setCardno(String cardno) {
		this.cardno = cardno;
	}

}