package cn.gc80.datamodel.sysbase;

/**
 * YfssSysUserRole generated by MyEclipse Persistence Tools
 */

public class SysUserRole implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -1644087965952470203L;

	private String id;

	private SysAdmin sysUser;

	private SysRole sysRole;

	// Constructors

	/** default constructor */
	public SysUserRole() {
	}

	public SysUserRole(String roleid) {
		SysRole role = new SysRole();
		role.setId(roleid);
		this.setSysRole(role);
	}
	/** full constructor */
	public SysUserRole(SysAdmin sysUser, SysRole sysRole) {
		this.sysUser = sysUser;
		this.sysRole = sysRole;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SysRole getSysRole() {
		return sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	public SysAdmin getSysUser() {
		return sysUser;
	}

	public void setSysUser(SysAdmin sysUser) {
		this.sysUser = sysUser;
	}

}