package cn.gc80.datamodel.exam;

import java.util.Set;

import cn.gc80.datamodel.sysbase.SysCode;

/**
 * examPaperQuestion generated by MyEclipse Persistence Tools
 */

public class ExamPaperQuestion implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 7585750383922427754L;

	private String id;

	private ExamQuestion examQuestion;

	private ExamPaper examPaper;

	private Long grade;

	// Constructors

	/** default constructor */
	public ExamPaperQuestion() {
	}

	/** minimal constructor */
	public ExamPaperQuestion(String questionid,String answers,Long grade) {
		this.grade = grade;
		ExamQuestion question = new ExamQuestion();
		question.setId(questionid);
		question.setAnswers(answers);
		this.examQuestion = question;
	}

	/** full constructor */
	public ExamPaperQuestion(ExamQuestion examQuestion,
			ExamPaper examPaper, Long grade) {
		this.examQuestion = examQuestion;
		this.examPaper = examPaper;
		this.grade = grade;
	}

	public ExamPaperQuestion(String id,String questionid,String queCodeid,String codeName,String title,String content,Set examQueOptions,String paperid){
		this.id = id;
		ExamQuestion question = new ExamQuestion();
		question.setId(questionid);
		SysCode code = new SysCode();
		code.setId(queCodeid);
		code.setCodeName(codeName);
		question.setSysCode(code);
		question.setTitle(title);
		question.setContent(content);
		question.setExamQueOptions(examQueOptions);
		this.examQuestion = question;
		ExamPaper paper = new ExamPaper();
		paper.setId(paperid);
		this.examPaper = paper;
	}
	
	
	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public ExamQuestion getExamQuestion() {
		return this.examQuestion;
	}

	public void setExamQuestion(ExamQuestion examQuestion) {
		this.examQuestion = examQuestion;
	}

	public ExamPaper getExamPaper() {
		return this.examPaper;
	}

	public void setExamPaper(ExamPaper examPaper) {
		this.examPaper = examPaper;
	}

	public Long getGrade() {
		return this.grade;
	}

	public void setGrade(Long grade) {
		this.grade = grade;
	}

}