package cn.gc80.datamodel.exam;

import cn.gc80.datamodel.aq.AqQuestion;
import cn.gc80.datamodel.res.ResChapter;
import cn.gc80.datamodel.res.ResCourse;
import cn.gc80.datamodel.res.ResCourseware;
import cn.gc80.datamodel.sysbase.SysUser;

/**
 * YfssExamUserHouse generated by MyEclipse Persistence Tools
 */

public class ExamUserHouse implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 6536462184990998635L;

	private String id;

	private ResCourse resCourse;

	private SysUser sysUser;

	private ResChapter resChapter;

	private AqQuestion aqQuestion;

	private ResCourseware resCourseware;

	private ExamQuestion examQuestion;

	private ExamPaper examPaper;

	private String housetime;

	private String type;

	// Constructors

	/** default constructor */
	public ExamUserHouse() {
	}

	/** full constructor */
	public ExamUserHouse(ResCourse resCourse,
			SysUser sysUser, ResChapter resChapter,
			AqQuestion aqQuestion, ResCourseware resCourseware,
			ExamQuestion examQuestion, ExamPaper examPaper,
			String housetime, String type) {
		this.resCourse = resCourse;
		this.sysUser = sysUser;
		this.resChapter = resChapter;
		this.aqQuestion = aqQuestion;
		this.resCourseware = resCourseware;
		this.examQuestion = examQuestion;
		this.examPaper = examPaper;
		this.housetime = housetime;
		this.type = type;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public AqQuestion getAqQuestion() {
		return this.aqQuestion;
	}

	public void setAqQuestion(AqQuestion aqQuestion) {
		this.aqQuestion = aqQuestion;
	}

	public String getHousetime() {
		return this.housetime;
	}

	public void setHousetime(String housetime) {
		this.housetime = housetime;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public ResChapter getResChapter() {
		return resChapter;
	}

	public void setResChapter(ResChapter resChapter) {
		this.resChapter = resChapter;
	}

	public ResCourse getResCourse() {
		return resCourse;
	}

	public void setResCourse(ResCourse resCourse) {
		this.resCourse = resCourse;
	}

	public ResCourseware getResCourseware() {
		return resCourseware;
	}

	public void setResCourseware(ResCourseware resCourseware) {
		this.resCourseware = resCourseware;
	}

	public ExamPaper getExamPaper() {
		return examPaper;
	}

	public void setExamPaper(ExamPaper examPaper) {
		this.examPaper = examPaper;
	}

	public ExamQuestion getExamQuestion() {
		return examQuestion;
	}

	public void setExamQuestion(ExamQuestion examQuestion) {
		this.examQuestion = examQuestion;
	}

	public SysUser getSysUser() {
		return sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

}