package cn.gc80.datamodel.business;

import cn.gc80.datamodel.res.ResBook;
import cn.gc80.datamodel.res.ResCourse;
import cn.gc80.datamodel.sysbase.SysCode;
import cn.gc80.datamodel.sysbase.SysProperty;
import cn.gc80.datamodel.sysbase.SysProvince;
import cn.gc80.datamodel.sysbase.SysTeacher;
import cn.gc80.datamodel.sysbase.SysUser;
import cn.gc80.datamodel.training.TrainClass;
import cn.gc80.datamodel.training.TrainProject;

/**
 * YfssEOrderDetail generated by MyEclipse Persistence Tools
 */

public class EOrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = 4636983830861457245L;

	private String id;

	private ResCourse resCourse;
	
	private TrainProject trainProject;

	private SysUser sysUser;

	private ResBook resBook;

	private EOrder order;

	private Long amount = 0l;
	
	private Long hasCredit=0l;

	private Double price = 0d;
	
	private String delflag = "";
	
	private String year;
	
	private Double examscore;
	
	private String studystatus;
	
	private String isSubItem;
	
	private String isExam;
	// Constructors
	
	private Long goodNum;
	
	private Long studyNum;
	
	//班级ID
	private TrainClass trainClass;
	//学号
	private String studyNo;
	
	private Long credit;
	//是否分配评价
	private String isEva;
	
	public String getIsExam() {
		return isExam;
	}

	public void setIsExam(String isExam) {
		this.isExam = isExam;
	}

	

	public Long getGoodNum() {
		return goodNum;
	}

	public void setGoodNum(Long goodNum) {
		this.goodNum = goodNum;
	}

	public Long getStudyNum() {
		return studyNum;
	}

	public void setStudyNum(Long studyNum) {
		this.studyNum = studyNum;
	}

	public String getIsSubItem() {
		return isSubItem;
	}

	public void setIsSubItem(String isSubItem) {
		this.isSubItem = isSubItem;
	}

	public String getStudystatus() {
		return studystatus;
	}

	public void setStudystatus(String studystatus) {
		this.studystatus = studystatus;
	}

	public void setHasCredit(Long hasCredit) {
		this.hasCredit = hasCredit;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getDelflag() {
		return delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	/** default constructor */
	public EOrderDetail() {
	}

	/** minimal constructor */
	
	public EOrderDetail(String id,Long hasCredit) {
		this.id = id;
		this.hasCredit = hasCredit;
	}
	public EOrderDetail(String id,Long hasCredit,String studystatus) {
		this.id = id;
		this.hasCredit = hasCredit;
		this.studystatus = studystatus;
	}
	public EOrderDetail(String id,Long hasCredit,String studystatus,String year) {
		this.id = id;
		this.hasCredit = hasCredit;
		this.studystatus = studystatus;
		this.year = year;
	}
	public EOrderDetail(String id,Long hasCredit,String studystatus,String year,String isExam) {
		this.id = id;
		this.hasCredit = hasCredit;
		this.studystatus = studystatus;
		this.year = year;
		this.isExam = isExam;
	}
	public EOrderDetail(String id,Double price,String courseid,String CNo,String CName) {
		this.id = id;
		this.price = price;
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCNo(CNo);
		course.setCName(CName);
		this.resCourse = course;
	}
	
	public EOrderDetail(String id,Double price,Long amount,String courseid,String CNo,Long CCredithour,Double CPeriod,Long CDuration,String CName) {
		this.id = id;
		this.price = price;
		this.amount = amount;
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCNo(CNo);
		course.setCName(CName);
		course.setCCredithour(CCredithour);
		course.setCPeriod(CPeriod);
		course.setCDuration(CDuration);
		this.resCourse = course;
		
	}
	
	public EOrderDetail(String id,String courseid,String CNo,String CName,Long CCredithour,String codeNo,String isExam,Long hasCredit,String studystatus,String year) {
		this.id = id;
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCNo(CNo);
		course.setCName(CName);
		course.setCCredithour(CCredithour);
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		course.setSysCode(code);
		course.setIsExam(isExam);
		this.resCourse = course;
		this.hasCredit = hasCredit;
		this.studystatus = studystatus;
		this.year=year;
		
	}
	
	public EOrderDetail(String id,Double price,Long amount,String bookid,String bookName) {
		this.id = id;
		this.price = price;
		this.amount = amount;
		ResBook book = new ResBook();
		book.setId(bookid);
		book.setBookName(bookName);
		this.resBook = book;
	}
	public EOrderDetail(String id,Double price,String courseid,String CName,String orderid,String ordNo,Double ordMoneysum,String ordPaytype,String userid,String realname,String ordStatus,String createtime,String ordPaytime){
		this.id = id;
		this.price = price;
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		this.resCourse = course;
		EOrder order = new EOrder();
		order.setId(orderid);
		order.setOrdNo(ordNo);
		order.setOrdMoneysum(ordMoneysum);
		order.setOrdStatus(ordStatus);
		order.setOrdPaytype(ordPaytype);
		order.setCreatetime(createtime);
		order.setOrdPaytime(ordPaytime);
		this.order = order;
		SysUser user = new SysUser();
		user.setId(userid);
		user.setRealname(realname);
		this.sysUser = user;
	}
	
	public EOrderDetail(String id,Double price,String courseid,String CName,String orderid,String ordNo,Double ordMoneysum,String ordPaytype,String userid,String userName,String realname,String ordStatus,String createtime,String ordPaytime){
		this.id = id;
		this.price = price;
		ResCourse course = new ResCourse();
		course.setId(courseid);
		course.setCName(CName);
		this.resCourse = course;
		EOrder order = new EOrder();
		order.setId(orderid);
		order.setOrdNo(ordNo);
		order.setOrdMoneysum(ordMoneysum);
		order.setOrdStatus(ordStatus);
		order.setOrdPaytype(ordPaytype);
		order.setCreatetime(createtime);
		order.setOrdPaytime(ordPaytime);
		this.order = order;
		SysUser user = new SysUser();
		user.setId(userid);
		user.setUserName(userName);
		user.setRealname(realname);
		this.sysUser = user;
	}
	
	public EOrderDetail(SysUser sysUser, EOrder order) {
		this.sysUser = sysUser;
		this.order = order;
	}

	/** full constructor */
	public EOrderDetail(ResCourse resCourse,
			SysUser sysUser, ResBook resBook,
			EOrder order, Long amount) {
		this.resCourse = resCourse;
		this.sysUser = sysUser;
		this.resBook = resBook;
		this.order = order;
		this.amount = amount;
	}
	
	public EOrderDetail(String userId,String year,String codeNo, Long hasCredit) {
		SysUser sysUser =new SysUser();
		sysUser.setId(userId);
		this.sysUser = sysUser;
		this.year=year;
		SysCode sysCode=new SysCode();
		sysCode.setCodeNo(codeNo);
		ResCourse resCourse=new ResCourse();
		resCourse.setSysCode(sysCode);
		this.resCourse=resCourse;
		this.hasCredit=hasCredit;
	}
	
	public EOrderDetail(String courseId,String CName,String tName,Long CCredithour,Double CPrice,String CNo,String CImage,String codeAlias,String codeName){
		SysCode sysCode=new SysCode();
		sysCode.setCodeName(codeName);
		sysCode.setCodeAlias(codeAlias);
		ResCourse resCourse=new ResCourse();
		resCourse.setSysCode(sysCode);
		resCourse.setId(courseId);
		resCourse.setCName(CName);
		resCourse.setCCredithour(CCredithour);
		resCourse.setCPrice(CPrice);
		resCourse.setCNo(CNo);
		resCourse.setCImage(CImage);
		SysTeacher sysTeacher=new SysTeacher();
		sysTeacher.setRealname(tName);
		resCourse.setSysTeacher(sysTeacher);
		this.resCourse=resCourse;
	}

	// Property accessors

	public  EOrderDetail(String id,String courseName, String className) {
		this.id = id;
		ResCourse resCourse =new ResCourse();
		resCourse.setCName(courseName);
		this.resCourse = resCourse;
		TrainClass trainClass=new TrainClass();
		trainClass.setClassName(className);
		this.trainClass = trainClass;
	}
	
	public EOrderDetail(String classId) {
		TrainClass trainClass=new TrainClass();
		trainClass.setId(classId);
		this.trainClass = trainClass;
	}
	
	public EOrderDetail(String id,String className) {
		this.id=id;
		TrainClass trainClass=new TrainClass();
		trainClass.setClassName(className);
		this.trainClass = trainClass;
	}
	
	public EOrderDetail(String id,String className,String studyNo,String year) {
		this.id=id;
		TrainClass trainClass=new TrainClass();
		trainClass.setClassName(className);
		this.trainClass = trainClass;
		this.studyNo=studyNo;
		this.year=year;
	}
	
	public EOrderDetail(String classId,String className,String codeName,String userId,String realname,String cardno,String year) {
		TrainClass trainClass=new TrainClass();
		trainClass.setId(classId);
		trainClass.setClassName(className);
		TrainProject trainProject =new TrainProject();
		SysCode sysCode=new SysCode();
		SysCode c=new SysCode();
		c.setCodeName(codeName);
		sysCode.setSysCode(c);
		trainProject.setSysCode(sysCode);
		trainClass.setTrainProject(trainProject);
		this.trainClass = trainClass;
		SysUser sysUser= new SysUser();
		sysUser.setId(userId);
		sysUser.setRealname(realname);
		sysUser.setCardno(cardno);
		this.sysUser = sysUser;
		this.year=year;
	}
	
	public EOrderDetail(String CId,String CNo,String CName,String CImage,Long CCredithour,Long hasCredit,String studystatus){
		ResCourse resCourse=new ResCourse();
		resCourse.setId(CId);
		resCourse.setCNo(CNo);
		resCourse.setCName(CName);
		resCourse.setCImage(CImage);
		resCourse.setCCredithour(CCredithour);
		this.resCourse=resCourse;
		this.hasCredit=hasCredit;
		this.studystatus=studystatus;
	}
	
	public EOrderDetail(String CId,String CNo,String CName,String CImage,Long CCredithour,Long hasCredit,String studystatus,String isExam){
		ResCourse resCourse=new ResCourse();
		resCourse.setId(CId);
		resCourse.setCNo(CNo);
		resCourse.setCName(CName);
		resCourse.setCImage(CImage);
		resCourse.setCCredithour(CCredithour);
		this.resCourse=resCourse;
		this.hasCredit=hasCredit;
		this.studystatus=studystatus;
		this.isExam=isExam;
	}
	
	public EOrderDetail(String id,String courseId,String CNo,String CName,Long CCredithour,String codeNo,String isExam,Long hasCredit,String studystatus,String year,String isSubItem,String projectId,String classId,Long classCredithour) {
		this.id = id;
		ResCourse course = new ResCourse();
		course.setId(courseId);
		course.setCNo(CNo);
		course.setCName(CName);
		course.setCCredithour(CCredithour);
		SysCode code = new SysCode();
		code.setCodeNo(codeNo);
		course.setSysCode(code);
		course.setIsExam(isExam);
		this.resCourse = course;
		this.hasCredit = hasCredit;
		this.studystatus = studystatus;
		this.year=year;
		this.isExam=isExam;
		this.isSubItem=isSubItem;
		TrainProject trainProject=new TrainProject();
		trainProject.setId(projectId);
		this.trainProject=trainProject;
		TrainClass trainClass=new TrainClass();
		trainClass.setId(classId);
		trainClass.setClassCredithour(classCredithour);
		this.trainClass=trainClass;
	}
	
	public EOrderDetail(String classId,String className,String codeName,String year,String studyNo) {
		TrainClass trainClass=new TrainClass();
		trainClass.setId(classId);
		trainClass.setClassName(className);
		TrainProject trainProject =new TrainProject();
		SysCode sysCode=new SysCode();
		SysCode c=new SysCode();
		c.setCodeName(codeName);
		sysCode.setSysCode(c);
		trainProject.setSysCode(sysCode);
		trainClass.setTrainProject(trainProject);
		this.trainClass = trainClass;
		this.year=year;
		this.studyNo=studyNo;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public EOrder getOrder() {
		return this.order;
	}

	public void setOrder(EOrder order) {
		this.order = order;
	}

	public ResBook getResBook() {
		return this.resBook;
	}

	public void setResBook(ResBook resBook) {
		this.resBook = resBook;
	}

	public ResCourse getResCourse() {
		return this.resCourse;
	}

	public void setResCourse(ResCourse resCourse) {
		this.resCourse = resCourse;
	}

	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getHasCredit() {
		return hasCredit;
	}

	public void setHascredit(Long hasCredit) {
		this.hasCredit = hasCredit;
	}

	public TrainProject getTrainProject() {
		return trainProject;
	}

	public void setTrainProject(TrainProject trainProject) {
		this.trainProject = trainProject;
	}

	public Double getExamscore() {
		return examscore;
	}

	public void setExamscore(Double examscore) {
		this.examscore = examscore;
	}


	public TrainClass getTrainClass() {
		return trainClass;
	}

	public void setTrainClass(TrainClass trainClass) {
		this.trainClass = trainClass;
	}

	public String getStudyNo() {
		return studyNo;
	}

	public void setStudyNo(String studyNo) {
		this.studyNo = studyNo;
	}

	public Long getCredit() {
		return credit;
	}

	public void setCredit(Long credit) {
		this.credit = credit;
	}

	public String getIsEva() {
		return isEva;
	}

	public void setIsEva(String isEva) {
		this.isEva = isEva;
	}
}