package cn.gc80.datamodel.business;

/**
 * EOrderLog generated by MyEclipse Persistence Tools
 */

public class EOrderLog implements java.io.Serializable {

	private static final long serialVersionUID = -4776198526104578069L;

	private String id;

	private EOrder order;

	private String ordStatus;

	private Double ordMoneysum;

	private String ordPaytype;

	private String ordLogTime;

	private String ordLogOperator;
	
	private String memo;

	// Constructors

	/** default constructor */
	public EOrderLog() {
	}

	/** minimal constructor */
	public EOrderLog(EOrder order, String ordStatus,
			String ordLogTime, String ordLogOperator) {
		this.order = order;
		this.ordStatus = ordStatus;
		this.ordLogTime = ordLogTime;
		this.ordLogOperator = ordLogOperator;
	}

	/** full constructor */
	public EOrderLog(EOrder order, String ordStatus,
			Double ordMoneysum, String ordPaytype, String ordLogTime,
			String ordLogOperator) {
		this.order = order;
		this.ordStatus = ordStatus;
		this.ordMoneysum = ordMoneysum;
		this.ordPaytype = ordPaytype;
		this.ordLogTime = ordLogTime;
		this.ordLogOperator = ordLogOperator;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrdStatus() {
		return this.ordStatus;
	}

	public void setOrdStatus(String ordStatus) {
		this.ordStatus = ordStatus;
	}

	public Double getOrdMoneysum() {
		return this.ordMoneysum;
	}

	public void setOrdMoneysum(Double ordMoneysum) {
		this.ordMoneysum = ordMoneysum;
	}

	public String getOrdPaytype() {
		return this.ordPaytype;
	}

	public void setOrdPaytype(String ordPaytype) {
		this.ordPaytype = ordPaytype;
	}

	public String getOrdLogTime() {
		return this.ordLogTime;
	}

	public void setOrdLogTime(String ordLogTime) {
		this.ordLogTime = ordLogTime;
	}

	public String getOrdLogOperator() {
		return this.ordLogOperator;
	}

	public void setOrdLogOperator(String ordLogOperator) {
		this.ordLogOperator = ordLogOperator;
	}

	public EOrder getOrder() {
		return order;
	}

	public void setOrder(EOrder order) {
		this.order = order;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

}