package cn.gc80.datamodel.aq;

import java.util.HashSet;
import java.util.Set;

import cn.gc80.datamodel.exam.ExamPaper;
import cn.gc80.datamodel.exam.ExamQuestion;
import cn.gc80.datamodel.exam.ExamQuiz;
import cn.gc80.datamodel.res.ResChapter;
import cn.gc80.datamodel.res.ResCourse;
import cn.gc80.datamodel.res.ResCourseware;
import cn.gc80.datamodel.sysbase.SysCode;
import cn.gc80.datamodel.sysbase.SysUser;

/**
 * AqQuestion generated by MyEclipse Persistence Tools
 */

public class AqQuestion implements java.io.Serializable {
	private static final long serialVersionUID = -5626782401361002451L;

	private String id;

	private ResCourse resCourse;

	private SysUser sysUser;

	private ResChapter resChapter;

	private ResCourseware resCourseware;

	private SysCode sysCode;

	private AqQuestion aqQuestion;
	
	private ExamPaper examPaper;
	
	private ExamQuiz examQuiz;
	
	private ExamQuestion examQuestion;

	private String title;

	private String content;

	private String status;

	private String viewStatus;
	
	private String normalStatus;

	private String createtime;

	private String lastedittime;

	private String creator;

	private String lasteditor;

	private String delflag;

	private Set examUserHouses = new HashSet(0);

	private Set aqAnswers = new HashSet(0);

	private Set aqQuestions = new HashSet(0);

	// Constructors

	/** default constructor */
	public AqQuestion() {
	}

	/** minimal constructor */
	public AqQuestion(String title, String content, String delflag) {
		this.title = title;
		this.content = content;
		this.delflag = delflag;
	}

	/** full constructor */
	public AqQuestion(ResCourse resCourse, SysUser sysUser,
			ResChapter resChapter, ResCourseware resCourseware,
			SysCode sysCode, AqQuestion aqQuestion,
			String title, String content, String status, String viewStatus,
			String createtime, String lastedittime, String creator,
			String lasteditor, String delflag, Set examUserHouses,
			Set aqAnswers, Set aqQuestions) {
		this.resCourse = resCourse;
		this.sysUser = sysUser;
		this.resChapter = resChapter;
		this.resCourseware = resCourseware;
		this.sysCode = sysCode;
		this.aqQuestion = aqQuestion;
		this.title = title;
		this.content = content;
		this.status = status;
		this.viewStatus = viewStatus;
		this.createtime = createtime;
		this.lastedittime = lastedittime;
		this.creator = creator;
		this.lasteditor = lasteditor;
		this.delflag = delflag;
		this.examUserHouses = examUserHouses;
		this.aqAnswers = aqAnswers;
		this.aqQuestions = aqQuestions;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public ExamPaper getExamPaper() {
		return examPaper;
	}

	public void setExamPaper(ExamPaper examPaper) {
		this.examPaper = examPaper;
	}

	public ExamQuestion getExamQuestion() {
		return examQuestion;
	}

	public void setExamQuestion(ExamQuestion examQuestion) {
		this.examQuestion = examQuestion;
	}

	public AqQuestion getAqQuestion() {
		return this.aqQuestion;
	}

	public void setAqQuestion(AqQuestion aqQuestion) {
		this.aqQuestion = aqQuestion;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getViewStatus() {
		return this.viewStatus;
	}

	public void setViewStatus(String viewStatus) {
		this.viewStatus = viewStatus;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getLastedittime() {
		return this.lastedittime;
	}

	public void setLastedittime(String lastedittime) {
		this.lastedittime = lastedittime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getLasteditor() {
		return this.lasteditor;
	}

	public void setLasteditor(String lasteditor) {
		this.lasteditor = lasteditor;
	}

	public String getDelflag() {
		return this.delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}


	public Set getAqAnswers() {
		return aqAnswers;
	}

	public void setAqAnswers(Set aqAnswers) {
		this.aqAnswers = aqAnswers;
	}

	public Set getAqQuestions() {
		return aqQuestions;
	}

	public void setAqQuestions(Set aqQuestions) {
		this.aqQuestions = aqQuestions;
	}

	public ExamQuiz getExamQuiz() {
		return examQuiz;
	}

	public void setExamQuiz(ExamQuiz examQuiz) {
		this.examQuiz = examQuiz;
	}

	public Set getExamUserHouses() {
		return examUserHouses;
	}

	public void setExamUserHouses(Set examUserHouses) {
		this.examUserHouses = examUserHouses;
	}

	public ResChapter getResChapter() {
		return resChapter;
	}

	public void setResChapter(ResChapter resChapter) {
		this.resChapter = resChapter;
	}

	public ResCourse getResCourse() {
		return resCourse;
	}

	public void setResCourse(ResCourse resCourse) {
		this.resCourse = resCourse;
	}

	public ResCourseware getResCourseware() {
		return resCourseware;
	}

	public void setResCourseware(ResCourseware resCourseware) {
		this.resCourseware = resCourseware;
	}

	public SysCode getSysCode() {
		return sysCode;
	}

	public void setSysCode(SysCode sysCode) {
		this.sysCode = sysCode;
	}

	public SysUser getSysUser() {
		return sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public String getNormalStatus() {
		return normalStatus;
	}

	public void setNormalStatus(String normalStatus) {
		this.normalStatus = normalStatus;
	}

}