package cn.gc80.datamodel.res;

/**
 * ResCouCw generated by MyEclipse Persistence Tools
 */

public class ResCouCw implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 5161532260299661790L;

	private String id;

	private ResCourse resCourse;

	private ResCourseware resCourseware;

	// Constructors

	/** default constructor */
	public ResCouCw() {
	}

	
	public ResCouCw(String cwid,String cwReleaseDir,String cwShowUrl){
		ResCourseware cw = new ResCourseware();
		cw.setId(cwid);
		cw.setCwReleaseDir(cwReleaseDir);
		cw.setCwShowUrl(cwShowUrl);
		this.resCourseware = cw;
	}
	
	public ResCouCw(String id,String coursewareid){
		this.id = id;
		ResCourseware cw = new ResCourseware();
		cw.setId(coursewareid);
		this.resCourseware = cw;
	}
	public ResCouCw(String id,String coursewareid,Long cwAllowAttempt){
		this.id = id;
		ResCourseware cw = new ResCourseware();
		cw.setId(coursewareid);
		cw.setCwAllowAttempt(cwAllowAttempt);
		this.resCourseware = cw;
	}
	/** full constructor */
	public ResCouCw(ResCourse resCourse,
			ResCourseware resCourseware) {
		this.resCourse = resCourse;
		this.resCourseware = resCourseware;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public ResCourse getResCourse() {
		return this.resCourse;
	}

	public void setResCourse(ResCourse resCourse) {
		this.resCourse = resCourse;
	}

	public ResCourseware getResCourseware() {
		return this.resCourseware;
	}

	public void setResCourseware(ResCourseware resCourseware) {
		this.resCourseware = resCourseware;
	}


	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

}